local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "dwarf" then
    LiveGuide.registerLevel({
        guide = "LiveGuideDwarf",
        race = "dwarf",
        title = "20-21",
        level = 20,
        nextLevel = 21,
        steps = function()
            return {
                { class = "R", action = 20, questName = "Alther's Mill", x = 0.285, y = 0.520, mapId = 1433, npcName = "Lucius", questId = 2282, },
                { class = "R", action = 26, questName = "Horns of Nez'ra", x = 0.281, y = 0.523, mapId = 1433, npcName = "Arantir", questId = 2358, },
                { action = 20, questName = "Redridge Goulash", x = 0.227, y = 0.438, mapId = 1433, npcName = "Chef Breanna", questId = 92, },
                { action = 26, questName = "An Unwelcome Guest", x = 0.219, y = 0.463, mapId = 1433, npcName = "Martie Jainrose", questId = 34, },
                { action = 8, questName = "An Unwelcome Guest", x = 0.157, y = 0.493, mapId = 1433, npcName = "Bellygrub", questId = 34, },
                { action = 20, questName = "An Unwelcome Guest", x = 0.219, y = 0.463, mapId = 1433, npcName = "Martie Jainrose", questId = 34, },
                { action = 16, questName = "to Darkshire", x = 0.306, y = 0.594, mapId = 1433, npcName = "Ariena Stormfeather", },
                { action = 6, questName = "[Bronze Tube]", x = 0.780, y = 0.483, mapId = 1431, npcName = "Herble Baubbletump", notes = "If you don't already have one. Needed for Darkshire quest.", amount = "1", },
                { action = 26, questName = "Raven Hill", x = 0.753, y = 0.487, mapId = 1431, npcName = "Elaine Carevin", questId = 163, },
                { action = 26, questName = "Deliveries to Sven", x = 0.753, y = 0.487, mapId = 1431, npcName = "Elaine Carevin", questId = 164, },
                { action = 26, questName = "The Hermit", x = 0.753, y = 0.487, mapId = 1431, npcName = "Elaine Carevin", questId = 165, },
                { action = 26, questName = "The Totem of Infliction", x = 0.758, y = 0.453, mapId = 1431, npcName = "Madame Eva", questId = 101, },
                { action = 26, questName = "The Night Watch", x = 0.736, y = 0.469, mapId = 1431, npcName = "Commander Althea Ebonlocke", questId = 56, },
                { action = 26, questName = "Eight-Legged Menaces", x = 0.451, y = 0.670, mapId = 1431, npcName = "Watcher Dodds", questId = 245, },
                { class = "D", action = 54, questName = "to Moonglade", x = 0.451, y = 0.670, mapId = 1431, npcName = "", },
                { class = "HMPaPrRLW", action = 22, questName = "to Stormwind", x = 0.451, y = 0.670, mapId = 1431, npcName = "", },
                { class = "D", action = 40, questName = "", x = 0.525, y = 0.406, mapId = 1450, npcName = "Loganaar", },
                { class = "D", action = 22, questName = "to Stormwind", npcName = "", },
                { action = 38, questName = "for Deadmines", npcName = "", },
                { action = 6, questName = "[Bronze Tube]", x = 0.536, y = 0.598, mapId = 1453, npcName = "Auctioneer Jaxon", notes = "If you don't already have one. Needed for Darkshire quest. Last chance.", amount = "1", },
                { class = "M", action = 40, questName = "", x = 0.369, y = 0.812, mapId = 1453, npcName = "Elsharin", },
                { class = "M", action = 40, questName = "Teleport: Stormwind", x = 0.398, y = 0.794, mapId = 1453, npcName = "Larimaine Purdue", },
                { class = "L", action = 40, questName = "", x = 0.261, y = 0.772, mapId = 1453, npcName = "Ursula Deline", },
                { class = "L", action = 40, questName = "Pet", x = 0.257, y = 0.777, mapId = 1453, npcName = "Spackle Thornberry", },
                { class = "L", action = 26, questName = "Devourer of Souls", x = 0.252, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1716, },
                { action = 26, questName = "Speaking of Fortitude", x = 0.457, y = 0.384, mapId = 1453, npcName = "Brother Kristoff", questId = 343, },
                { action = 35, questName = "Tinkmaster Overspark", x = 0.405, y = 0.309, mapId = 1453, npcName = "Brother Sarno", questId = 2923, },
                { class = "H", action = 40, questName = "", x = 0.616, y = 0.152, mapId = 1453, npcName = "Einris Brightspear", },
                { class = "Pa", action = 40, questName = "", x = 0.387, y = 0.329, mapId = 1453, npcName = "Arthur the Faithful", },
                { class = "Pr", action = 40, questName = "", x = 0.412, y = 0.282, mapId = 1453, npcName = "Brother Benjamin", },
                { action = 20, questName = "Speaking of Fortitude", x = 0.742, y = 0.075, mapId = 1453, npcName = "Milton Sheaf", questId = 343, },
                { action = 26, questName = "Brother Paxton", x = 0.742, y = 0.075, mapId = 1453, npcName = "Milton Sheaf", questId = 344, },
                { class = "R", action = 40, questName = "", x = 0.746, y = 0.528, mapId = 1453, npcName = "Osborne the Night Man", },
                { class = "R", action = 35, questName = "Mathias and the Defias", x = 0.758, y = 0.598, mapId = 1453, npcName = "Master Mathias Shaw", questId = 2360, },
                { class = "W", action = 40, questName = "", x = 0.787, y = 0.458, mapId = 1453, npcName = "Wu Shen", },
                { action = 6, questName = "[Stormwind Seasoning Herbs]", x = 0.642, y = 0.606, mapId = 1453, npcName = "Felicia Gump", amount = "1", },
                { action = 16, questName = "to Sentinel Hill", x = 0.663, y = 0.621, mapId = 1453, npcName = "Dungar Longdrink", },
                { action = 20, questName = "Messenger to Westfall", x = 0.563, y = 0.475, mapId = 1436, npcName = "Gryan Stoutmantle", questId = 143, },
                { action = 26, questName = "Messenger to Westfall (2)", x = 0.563, y = 0.475, mapId = 1436, npcName = "Gryan Stoutmantle", questId = 144, },
                { action = 26, questName = "Red Silk Bandanas", x = 0.567, y = 0.473, mapId = 1436, npcName = "Scout Riell", questId = 214, },
                { action = 33, questName = "at Sentinel Hill", x = 0.529, y = 0.537, mapId = 1436, npcName = "Innkeeper Heather", },
                { action = 18, questName = "to The Deadmines", x = 0.426, y = 0.717, mapId = 1436, npcName = "", },
                { action = 13, questName = "The Deadmines", x = 0.426, y = 0.717, mapId = 1436, npcName = "", },
                { action = 8, questName = "Collecting Memories", npcName = "", questId = 168, notes = "Outside the instance: ~41, 80", },
                { action = 8, questName = "Oh Brother. . .", npcName = "Foreman Thistlenettle", questId = 167, notes = "Outside the instance: 42.2, 82.6", },
                { action = 8, questName = "Red Silk Bandanas", npcName = "", questId = 214, },
                { action = 8, questName = "Underground Assault", npcName = "Sneed's Shredder", questId = 2040, },
                { action = 8, questName = "The Defias Brotherhood (7)", npcName = "Edwin VanCleef", questId = 166, },
                { action = 25, questName = "[An Unsent Letter]", npcName = "Edwin VanCleef", },
                { action = 22, questName = "to Sentinel Hill", npcName = "", },
                { action = 20, questName = "The Defias Brotherhood (7)", x = 0.563, y = 0.475, mapId = 1436, npcName = "Gryan Stoutmantle", questId = 166, },
                { action = 42, questName = "", x = 0.570, y = 0.472, mapId = 1436, npcName = "Quartermaster Lewis", },
                { action = 20, questName = "Red Silk Bandanas", x = 0.567, y = 0.473, mapId = 1436, npcName = "Scout Riell", questId = 214, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end