local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "undead" then
    LiveGuide.registerLevel({
        guide = "LiveGuideUndead",
        race = "undead",
        title = "17-18",
        level = 17,
        nextLevel = 18,
        steps = function()
            return {
                { action = 43, questName = "", x = 0.521, y = 0.621, mapId = 1454, npcName = "Kaja", },
                { action = 3, questName = "", x = 0.496, y = 0.691, mapId = 1454, npcName = "Karus", },
                { action = 40, questName = "First Aid", x = 0.342, y = 0.846, mapId = 1454, npcName = "Arnok", },
                { action = 18, questName = "out Orgrimmar Side Entrance", x = 0.175, y = 0.610, mapId = 1454, npcName = "", },
                { action = 18, questName = "to Ashenvale", x = 0.948, y = 0.772, mapId = 1440, npcName = "", },
                { action = 11, questName = "in Ashenvale", x = 0.910, y = 0.650, mapId = 1440, npcName = "", },
                { action = 36, questName = "at Nightsong Woods", x = 0.807, y = 0.584, mapId = 1440, npcName = "Spirit Healer", },
                { action = 17, questName = "at Splintertree Post", x = 0.732, y = 0.616, mapId = 1440, npcName = "Vhulgra", },
                { action = 18, questName = "to The Barrens", x = 0.685, y = 0.871, mapId = 1440, npcName = "", },
                { action = 26, questName = "The Warsong Reports", x = 0.481, y = 0.054, mapId = 1413, npcName = "Kadrak", questId = 6543, notes = "He's on the 2nd level of the watchtower. Quest requires level 17 to pick up. If you are not 17 yet, pick this up in a few minutes after you hand in Nugget Slugs.", },
                { action = 20, questName = "Wenikee Boltbucket", x = 0.491, y = 0.112, mapId = 1413, npcName = "Wenikee Boltbucket", questId = 3921, },
                { action = 26, questName = "Nugget Slugs", x = 0.491, y = 0.112, mapId = 1413, npcName = "Wenikee Boltbucket", questId = 3922, },
                { action = 28, questName = "Chen's Empty Keg (2)", x = 0.500, y = 0.130, mapId = 1413, npcName = "[Plainstrider Kidney]", questId = 821, },
                { class = "D", action = 29, questName = "Curing the Sick", x = 0.520, y = 0.130, mapId = 1413, npcName = "Sickly Gazelle", questId = 6129, },
                { action = 29, questName = "Nugget Slugs", x = 0.570, y = 0.070, mapId = 1413, npcName = "<Tool Bucket>", questId = 3922, },
                { action = 26, questName = "Ignition", x = 0.565, y = 0.075, mapId = 1413, npcName = "Wizzlecrank's Shredder", questId = 858, },
                { action = 8, questName = "Nugget Slugs", x = 0.600, y = 0.090, mapId = 1413, npcName = "<Tool Bucket>", questId = 3922, },
                { action = 8, questName = "Ignition", x = 0.563, y = 0.085, mapId = 1413, npcName = "Supervisor Lugwizzle", questId = 858, },
                { action = 20, questName = "Ignition", x = 0.565, y = 0.075, mapId = 1413, npcName = "Wizzlecrank's Shredder", questId = 858, },
                { action = 26, questName = "The Escape", x = 0.565, y = 0.075, mapId = 1413, npcName = "Wizzlecrank's Shredder", questId = 863, notes = "This is an escort quest. Do not accept this quest until all party members have handed in the previous quest.", },
                { action = 8, questName = "The Escape", x = 0.565, y = 0.075, mapId = 1413, npcName = "Wizzlecrank's Shredder", questId = 863, },
                { class = "D", action = 29, questName = "Curing the Sick", x = 0.520, y = 0.130, mapId = 1413, npcName = "Sickly Gazelle", questId = 6129, },
                { action = 20, questName = "Nugget Slugs", x = 0.491, y = 0.112, mapId = 1413, npcName = "Wenikee Boltbucket", questId = 3922, },
                { action = 26, questName = "Rilli Greasygob", x = 0.491, y = 0.112, mapId = 1413, npcName = "Wenikee Boltbucket", questId = 3923, },
                { action = 27, questName = "The Warsong Reports", x = 0.481, y = 0.054, mapId = 1413, npcName = "Kadrak", questId = 6543, notes = "Pick it up now if you couldn't grab it before.", },
                { action = 28, questName = "Chen's Empty Keg (2)", x = 0.450, y = 0.130, mapId = 1413, npcName = "[Plainstrider Kidney]", questId = 821, },
                { action = 29, questName = "Raptor Horns", x = 0.450, y = 0.130, mapId = 1413, npcName = "Sunscale Scytheclaw", questId = 865, },
                { class = "D", action = 29, questName = "Curing the Sick", x = 0.450, y = 0.130, mapId = 1413, npcName = "Sickly Gazelle", questId = 6129, },
                { action = 43, questName = "", x = 0.438, y = 0.122, mapId = 1413, npcName = "Vrang Wildgore", },
                { class = "W", action = 6, questName = "[Heavy Spiked Mace]", x = 0.438, y = 0.122, mapId = 1413, npcName = "Vrang Wildgore", notes = "If you still need.", },
                { action = 28, questName = "Chen's Empty Keg (2)", x = 0.430, y = 0.150, mapId = 1413, npcName = "[Plainstrider Kidney]", questId = 821, },
                { class = "D", action = 29, questName = "Curing the Sick", x = 0.430, y = 0.150, mapId = 1413, npcName = "Sickly Gazelle", questId = 6129, },
                { action = 8, questName = "Harpy Lieutenants", x = 0.400, y = 0.160, mapId = 1413, npcName = "Witchwing Slayer", questId = 875, notes = "Only the Slayers drop the quest item.", },
                { action = 7, questName = "Chen's Empty Keg (2)", x = 0.410, y = 0.210, mapId = 1413, npcName = "[Savannah Lion Tusk]", questId = 821, },
                { class = "D", action = 8, questName = "Curing the Sick", x = 0.410, y = 0.210, mapId = 1413, npcName = "Sickly Gazelle", questId = 6129, },
                { action = 8, questName = "Centaur Bracers", x = 0.420, y = 0.240, mapId = 1413, npcName = "", questId = 855, },
                { action = 20, questName = "Centaur Bracers", x = 0.454, y = 0.284, mapId = 1413, npcName = "Regthar Deathgate", questId = 855, },
                { action = 20, questName = "Verog the Dervish", x = 0.454, y = 0.284, mapId = 1413, npcName = "Regthar Deathgate", questId = 851, },
                { action = 26, questName = "Hezrul Bloodmark", x = 0.454, y = 0.284, mapId = 1413, npcName = "Regthar Deathgate", questId = 852, },
                { class = "D", action = 54, questName = "to Moonglade", x = 0.454, y = 0.284, mapId = 1413, npcName = "", },
                { class = "HMPrRSLW", action = 22, questName = "to Ratchet", x = 0.454, y = 0.284, mapId = 1413, npcName = "", },
                { class = "D", action = 20, questName = "A Lesson to Learn", x = 0.562, y = 0.306, mapId = 1450, npcName = "Dendrite Starblaze", questId = 26, },
                { class = "D", action = 26, questName = "Trial of the Lake", x = 0.562, y = 0.306, mapId = 1450, npcName = "Dendrite Starblaze", questId = 28, },
                { class = "D", action = 20, questName = "Curing the Sick", x = 0.562, y = 0.306, mapId = 1450, npcName = "Dendrite Starblaze", questId = 6129, },
                { class = "D", action = 26, questName = "Power over Poison", x = 0.562, y = 0.306, mapId = 1450, npcName = "Dendrite Starblaze", questId = 6130, },
                { class = "D", action = 29, questName = "Trial of the Lake", x = 0.530, y = 0.510, mapId = 1450, npcName = "<Bauble Container>", questId = 28, notes = "There are multiple locations in the lake for this item. Keep an eye out as you swim around.", },
                { class = "D", action = 41, questName = "[Shrine Bauble]", x = 0.365, y = 0.401, mapId = 1450, npcName = ">Shrine of Remulos<", },
                { class = "D", action = 20, questName = "Trial of the Lake", x = 0.365, y = 0.401, mapId = 1450, npcName = "Tajarri", questId = 28, },
                { class = "D", action = 26, questName = "Trial of the Sea Lion", x = 0.365, y = 0.401, mapId = 1450, npcName = "Tajarri", questId = 30, },
                { class = "D", action = 22, questName = "to Ratchet", x = 0.365, y = 0.401, mapId = 1450, npcName = "", },
                { action = 26, questName = "The Guns of Northwatch", x = 0.623, y = 0.390, mapId = 1413, npcName = "Captain Thalo'thas Brightsun", questId = 891, },
                { action = 43, questName = "", x = 0.622, y = 0.375, mapId = 1413, npcName = "Ironzar", },
                { action = 26, questName = "Deepmoss Spider Eggs", x = 0.624, y = 0.376, mapId = 1413, npcName = "Mebok Mizzyrix", questId = 1069, },
                { action = 3, questName = "", x = 0.626, y = 0.375, mapId = 1413, npcName = "Fuzruckle", },
                { action = 20, questName = "The Escape", x = 0.630, y = 0.372, mapId = 1413, npcName = "Sputtervalve", questId = 863, },
                { action = 26, questName = "Ziz Fizziks", x = 0.630, y = 0.372, mapId = 1413, npcName = "Sputtervalve", questId = 1483, },
                { action = 35, questName = "Trouble at the Docks", x = 0.631, y = 0.376, mapId = 1413, npcName = "Crane Operator Bigglefuzz", questId = 959, },
                { class = "R", action = 20, questName = "Wrenix of Ratchet", x = 0.631, y = 0.363, mapId = 1413, npcName = "Wrenix the Wretched", questId = 2382, },
                { class = "R", action = 26, questName = "Plundering the Plunderers", x = 0.631, y = 0.363, mapId = 1413, npcName = "Wrenix the Wretched", questId = 2381, },
                { class = "R", action = 8, questName = "Plundering the Plunderers", x = 0.631, y = 0.363, mapId = 1413, npcName = "Wrenix's Gizmotronic Apparatus", questId = 2381, notes = "Talk to it. Do it.", },
                { class = "R", action = 18, questName = "onto ship", x = 0.642, y = 0.455, mapId = 1413, npcName = "", notes = "30 min deviation to level Lockpicking. Party can grind at northwatch while you open boxes.", },
                { class = "R", action = 51, questName = "", x = 0.650, y = 0.455, mapId = 1413, npcName = "<Buccaneer's Strongbox>", notes = "One level below deck. Stand in a spot where you can reach 3 boxes. Keep practicing until your Lockpicking skill is at least 80 (need at least 25 to finish this quest).", },
                { class = "R", action = 51, questName = "", x = 0.650, y = 0.454, mapId = 1413, npcName = "<The Jewel of the Southsea>", notes = "Two levels below deck. WARNING, elite will spawn. have E.C.A.C. Keybound and ready to use.", },
                { class = "R", action = 41, questName = "[E.C.A.C.]", npcName = "Polly", },
                { class = "R", action = 8, questName = "Plundering the Plunderers", npcName = "Polly", questId = 2381, notes = "Use cooldowns. Don't lockpick again.", },
                { action = 8, questName = "The Guns of Northwatch", x = 0.610, y = 0.540, mapId = 1413, npcName = "", questId = 891, notes = "Kill the named mob at the top of each tower. You may need to find someone to help you kill Captain Fairmount.", },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end