local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "gnome" then
    LiveGuide.registerLevel({
        guide = "LiveGuideGnome",
        race = "gnome",
        title = "10-11",
        level = 10,
        nextLevel = 11,
        steps = function()
            return {
                { action = 33, questName = "at Thelsamar", x = 0.355, y = 0.484, mapId = 1432, npcName = "Innkeeper Hearthstove", },
                { action = 26, questName = "Honor Students", x = 0.370, y = 0.478, mapId = 1432, npcName = "Brock Stoneseeker", questId = 6387, },
                { action = 17, questName = "at Thelsamar", x = 0.339, y = 0.510, mapId = 1432, npcName = "Thorgrum Borrelson", },
                { action = 20, questName = "Honor Students", x = 0.339, y = 0.510, mapId = 1432, npcName = "Thorgrum Borrelson", questId = 6387, },
                { action = 26, questName = "Ride to Ironforge", x = 0.339, y = 0.510, mapId = 1432, npcName = "Thorgrum Borrelson", questId = 6391, },
                { action = 29, questName = "Rat Catching", x = 0.390, y = 0.230, mapId = 1432, npcName = "", questId = 416, },
                { action = 8, questName = "Rat Catching", x = 0.350, y = 0.160, mapId = 1432, npcName = "", questId = 416, },
                { action = 20, questName = "Mountaineer Stormpike's Task", x = 0.248, y = 0.184, mapId = 1432, npcName = "Mountaineer Stormpike", questId = 1339, },
                { action = 26, questName = "Stormpike's Order", x = 0.248, y = 0.184, mapId = 1432, npcName = "Mountaineer Stormpike", questId = 1338, },
                { action = 34, questName = "Filthy Paws", x = 0.248, y = 0.184, mapId = 1432, npcName = "Mountaineer Stormpike", questId = 307, },
                { action = 18, questName = "to North Gate Pass", x = 0.191, y = 0.174, mapId = 1432, npcName = "", },
                { action = 26, questName = "The Lost Pilot", x = 0.839, y = 0.392, mapId = 1426, npcName = "Pilot Hammerfoot", questId = 419, },
                { action = 20, questName = "The Lost Pilot", x = 0.797, y = 0.362, mapId = 1426, npcName = "<A Dwarven Corpse>", questId = 419, },
                { action = 26, questName = "A Pilot's Revenge", x = 0.797, y = 0.362, mapId = 1426, npcName = "<A Dwarven Corpse>", questId = 417, },
                { action = 7, questName = "A Pilot's Revenge", x = 0.783, y = 0.378, mapId = 1426, npcName = "Mangeclaw", questId = 417, },
                { action = 20, questName = "A Pilot's Revenge", x = 0.839, y = 0.392, mapId = 1426, npcName = "Pilot Hammerfoot", questId = 417, },
                { action = 11, questName = "", x = 0.839, y = 0.392, mapId = 1426, npcName = "", },
                { action = 36, questName = "at Kharanos", x = 0.473, y = 0.546, mapId = 1426, npcName = "Spirit Healer", },
                { action = 42, questName = "", x = 0.467, y = 0.536, mapId = 1426, npcName = "Golorn Frostbeard", },
                { class = "Pa", action = 40, questName = "", x = 0.476, y = 0.521, mapId = 1426, npcName = "Azar Stronghammer", },
                { class = "Pr", action = 26, questName = "Desperate Prayer", x = 0.473, y = 0.522, mapId = 1426, npcName = "Maxan Anvol", questId = 5639, },
                { class = "Pr", action = 40, questName = "", x = 0.473, y = 0.522, mapId = 1426, npcName = "Maxan Anvol", },
                { class = "M", action = 34, questName = "Speak with Bink", x = 0.475, y = 0.521, mapId = 1426, npcName = "Magis Sparkmantle", questId = 1879, notes = "We will do the human equivalent -- more XP.", },
                { class = "M", action = 40, questName = "", x = 0.475, y = 0.521, mapId = 1426, npcName = "Magis Sparkmantle", },
                { class = "H", action = 26, questName = "Taming the Beast", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6064, },
                { class = "H", action = 40, questName = "", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", },
                { class = "R", action = 26, questName = "Road to Salvation", x = 0.476, y = 0.526, mapId = 1426, npcName = "Hogral Bakkan", questId = 2218, },
                { class = "R", action = 40, questName = "", x = 0.476, y = 0.526, mapId = 1426, npcName = "Hogral Bakkan", },
                { class = "W", action = 34, questName = "Muren Stormpike", x = 0.474, y = 0.526, mapId = 1426, npcName = "Granis Swiftaxe", questId = 1679, notes = "We will do the human equivalent.", },
                { class = "W", action = 40, questName = "", x = 0.474, y = 0.526, mapId = 1426, npcName = "Granis Swiftaxe", },
                { class = "H", action = 8, questName = "Taming the Beast", x = 0.480, y = 0.560, mapId = 1426, npcName = "", questId = 6064, },
                { class = "H", action = 20, questName = "Taming the Beast", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6064, },
                { class = "H", action = 26, questName = "Taming the Beast (2)", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6084, },
                { class = "H", action = 8, questName = "Taming the Beast (2)", x = 0.490, y = 0.590, mapId = 1426, npcName = "", questId = 6084, },
                { class = "H", action = 20, questName = "Taming the Beast (2)", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6084, },
                { class = "H", action = 26, questName = "Taming the Beast (3)", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6085, },
                { class = "H", action = 8, questName = "Taming the Beast (3)", x = 0.470, y = 0.630, mapId = 1426, npcName = "", questId = 6085, },
                { class = "H", action = 20, questName = "Taming the Beast (3)", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6085, },
                { class = "H", action = 26, questName = "Training the Beast", x = 0.435, y = 0.538, mapId = 1426, npcName = "Grif Wildheart", questId = 6086, },
                { action = 18, questName = "to Ironforge", x = 0.215, y = 0.779, mapId = 1455, npcName = "", },
                { action = 20, questName = "The Reports", x = 0.395, y = 0.575, mapId = 1455, npcName = "Senator Barin Redstone", questId = 291, },
                { action = 20, questName = "Ride to Ironforge", x = 0.515, y = 0.263, mapId = 1455, npcName = "Golnir Bouldertoe", questId = 6391, },
                { action = 26, questName = "Gryth Thurden", x = 0.515, y = 0.263, mapId = 1455, npcName = "Golnir Bouldertoe", questId = 6388, },
                { action = 20, questName = "Gryth Thurden", x = 0.555, y = 0.477, mapId = 1455, npcName = "Gryth Thurden", questId = 6388, },
                { action = 26, questName = "Return to Brock", x = 0.555, y = 0.477, mapId = 1455, npcName = "Gryth Thurden", questId = 6392, },
                { class = "R", action = 20, questName = "Road to Salvation", x = 0.520, y = 0.148, mapId = 1455, npcName = "Hulfdan Blackbeard", questId = 2218, },
                { class = "R", action = 26, questName = "Simple Subterfugin'", x = 0.520, y = 0.148, mapId = 1455, npcName = "Hulfdan Blackbeard", questId = 2238, },
                { class = "R", action = 11, questName = "", x = 0.520, y = 0.148, mapId = 1455, npcName = "", notes = "Use unstuck if hearth still down, otherwise just run to Dun Morogh.", },
                { class = "L", action = 26, questName = "The Slaughtered Lamb", x = 0.476, y = 0.093, mapId = 1455, npcName = "Lago Blackwrench", questId = 1715, },
                { class = "L", action = 40, questName = "", x = 0.504, y = 0.057, mapId = 1455, npcName = "Briarthorn", },
                { class = "W", action = 40, questName = "Thrown", x = 0.622, y = 0.896, mapId = 1455, npcName = "Bixi Wobblebonk", },
                { class = "DHPaPrW", action = 40, questName = "Weapon Skills", x = 0.612, y = 0.895, mapId = 1455, npcName = "Buliwyf Stonehand", },
                { class = "H", action = 20, questName = "Training the Beast", x = 0.709, y = 0.858, mapId = 1455, npcName = "Belia Thundergranite", questId = 6086, },
                { class = "H", action = 40, questName = "Pet", x = 0.709, y = 0.858, mapId = 1455, npcName = "Belia Thundergranite", },
                { class = "DHMPaPrLW", action = 18, questName = "to Deeprun Tram", x = 0.770, y = 0.512, mapId = 1455, npcName = "", },
                { class = "R", action = 36, questName = "at Gates of Ironforge", x = 0.544, y = 0.392, mapId = 1426, npcName = "Spirit Healer", },
                { class = "R", action = 20, questName = "Simple Subterfugin'", x = 0.252, y = 0.445, mapId = 1426, npcName = "Onin MacHammar", questId = 2238, },
                { class = "R", action = 26, questName = "Onin's Report", x = 0.252, y = 0.445, mapId = 1426, npcName = "Onin MacHammar", questId = 2239, },
                { class = "R", action = 11, questName = "", npcName = "", },
                { class = "R", action = 36, questName = "at Kharanos", x = 0.473, y = 0.546, mapId = 1426, npcName = "Spirit Healer", },
                { class = "R", action = 20, questName = "Onin's Report", x = 0.520, y = 0.148, mapId = 1455, npcName = "Hulfdan Blackbeard", questId = 2239, },
                { class = "R", action = 18, questName = "to Deeprun Tram", x = 0.770, y = 0.512, mapId = 1455, npcName = "", },
                { action = 26, questName = "Deeprun Rat Roundup", x = 0.770, y = 0.512, mapId = 1455, npcName = "Monty", questId = 6661, },
                { action = 8, questName = "Deeprun Rat Roundup", npcName = "", questId = 6661, },
                { action = 20, questName = "Deeprun Rat Roundup", npcName = "Monty", questId = 6661, },
                { action = 26, questName = "Me Brother, Nipsy", npcName = "Monty", questId = 6662, },
                { action = 18, questName = "to Stormwind station", npcName = ">Deeprun Tram<", },
                { action = 20, questName = "Me Brother, Nipsy", npcName = "Nipsy", questId = 6662, },
                { action = 18, questName = "to Stormwind", npcName = "", },
                { action = 20, questName = "Stormpike's Order", x = 0.581, y = 0.165, mapId = 1453, npcName = "Furen Longbeard", questId = 1338, },
                { class = "Pr", action = 20, questName = "Desperate Prayer", x = 0.386, y = 0.280, mapId = 1453, npcName = "High Priestess Laurena", questId = 5639, },
                { class = "MPrL", action = 6, questName = "[Coarse Thread]", x = 0.433, y = 0.741, mapId = 1453, npcName = "Alexandra Bolero", notes = "Up to 9 required to craft wand. May not need all 9.", amount = "9", },
                { class = "MPrL", action = 40, questName = "Tailoring", x = 0.437, y = 0.737, mapId = 1453, npcName = "Lawrence Schneider", },
                { class = "MPrL", action = 52, questName = "[Bolt of Linen Cloth]", npcName = "", notes = "To 30 tailoring. If you don't have enough linen it's still possible to complete the wand if you have other green items to disenchant instead.", },
                { class = "MPrL", action = 40, questName = "[Brown Linen Robe]", x = 0.437, y = 0.737, mapId = 1453, npcName = "Lawrence Schneider", },
                { class = "MPrL", action = 40, questName = "Enchanting", x = 0.431, y = 0.637, mapId = 1453, npcName = "Betty Quin", },
                { class = "MPrL", action = 52, questName = "[Brown Linen Robe]", npcName = "", notes = "May not need all 9 to reach 10 Enchanting skill. Each disenchant gives a skill point.", amount = "9", },
                { class = "MPrL", action = 6, questName = "[Copper Rod]", x = 0.428, y = 0.644, mapId = 1453, npcName = "Jessara Cordell", amount = "1", },
                { class = "MPrL", action = 6, questName = "[Simple Wood]", x = 0.428, y = 0.644, mapId = 1453, npcName = "Jessara Cordell", amount = "1", },
                { class = "MPrL", action = 53, questName = "[Brown Linen Robe]", npcName = "", amount = "9", },
                { class = "MPrL", action = 52, questName = "[Runed Copper Rod]", npcName = "", notes = "This gives a skill if you craft it early enough, but you need Lesser Magic Essence which has a 20% chance from the robes, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH.", },
                { class = "MPrL", action = 40, questName = "[Lesser Magic Wand]", x = 0.431, y = 0.637, mapId = 1453, npcName = "Betty Quin", },
                { class = "MPrL", action = 52, questName = "[Lesser Magic Wand]", npcName = "", notes = "Lesser Magic Essence has a 20% chance from green gear, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH.", },
                { class = "L", action = 18, questName = "to The Slaughtered Lamb", x = 0.290, y = 0.743, mapId = 1453, npcName = "", },
                { class = "L", action = 20, questName = "The Slaughtered Lamb", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1715, },
                { class = "L", action = 26, questName = "Surena Caledon", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1688, },
                { class = "HPrLW", action = 40, questName = "Staves", x = 0.571, y = 0.577, mapId = 1453, npcName = "Woo Ping", },
                { action = 17, questName = "at Stormwind", x = 0.663, y = 0.621, mapId = 1453, npcName = "Dungar Longdrink", },
                { action = 18, questName = "down onto esports ledge", x = 0.660, y = 0.655, mapId = 1453, npcName = "", notes = "Fall onto the ledge below you. This is a much faster path to exit Stormwind. Take a moment to make sure you don't miss :^)", },
                { action = 18, questName = "along ledge to Valley of Heroes", x = 0.650, y = 0.680, mapId = 1453, npcName = "", },
                { action = 18, questName = "to Elwynn Forest", x = 0.717, y = 0.884, mapId = 1453, npcName = "", },
                { action = 18, questName = "to Elwynn Forest", x = 0.328, y = 0.504, mapId = 1429, npcName = "", },
                { class = "M", action = 26, questName = "Speak with Jennea", x = 0.432, y = 0.662, mapId = 1429, npcName = "Zaldimar Wefhellt", questId = 1860, },
                { action = 26, questName = "A Fishy Peril", x = 0.421, y = 0.673, mapId = 1429, npcName = "Remy 'Two Times'", questId = 40, },
                { action = 34, questName = "Gold Dust Exchange", x = 0.421, y = 0.673, mapId = 1429, npcName = "Remy 'Two Times'", questId = 47, },
                { action = 20, questName = "A Fishy Peril", x = 0.421, y = 0.659, mapId = 1429, npcName = "Marshal Dughan", questId = 40, },
                { action = 26, questName = "Further Concerns", x = 0.421, y = 0.659, mapId = 1429, npcName = "Marshal Dughan", questId = 35, },
                { action = 26, questName = "The Fargodeep Mine", x = 0.421, y = 0.659, mapId = 1429, npcName = "Marshal Dughan", questId = 62, },
                { action = 26, questName = "Elmore's Task", x = 0.417, y = 0.655, mapId = 1429, npcName = "Smith Argus", questId = 1097, },
                { class = "W", action = 26, questName = "A Warrior's Training", x = 0.411, y = 0.658, mapId = 1429, npcName = "Lyria Du Lac", questId = 1638, },
                { action = 26, questName = "Lost Necklace", x = 0.345, y = 0.843, mapId = 1429, npcName = "'Auntie' Bernice Stonefield", questId = 85, },
                { action = 26, questName = "Princess Must Die!", x = 0.347, y = 0.845, mapId = 1429, npcName = "Ma Stonefield", questId = 88, },
                { action = 20, questName = "Lost Necklace", x = 0.431, y = 0.857, mapId = 1429, npcName = "Billy Maclure", questId = 85, },
                { action = 26, questName = "Pie for Billy", x = 0.431, y = 0.857, mapId = 1429, npcName = "Billy Maclure", questId = 86, },
                { action = 26, questName = "Young Lovers", x = 0.432, y = 0.896, mapId = 1429, npcName = "Maybell Maclure", questId = 106, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end