local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "orc" then
    LiveGuide.registerLevel({
        guide = "LiveGuideOrc",
        race = "orc",
        title = "11-12",
        level = 11,
        nextLevel = 12,
        steps = function()
            return {
                { action = 28, questName = "Finding the Antidote", x = 0.550, y = 0.140, mapId = 1411, npcName = "Venomtail Scorpid", questId = 813, },
                { action = 20, questName = "Skull Rock", x = 0.564, y = 0.200, mapId = 1411, npcName = "Margoz", questId = 827, },
                { action = 26, questName = "Neeru Fireblade", x = 0.564, y = 0.200, mapId = 1411, npcName = "Margoz", questId = 829, },
                { action = 28, questName = "Finding the Antidote", x = 0.540, y = 0.150, mapId = 1411, npcName = "Venomtail Scorpid", questId = 813, },
                { action = 7, questName = "Finding the Antidote", x = 0.500, y = 0.170, mapId = 1411, npcName = "Venomtail Scorpid", questId = 813, },
                { action = 43, questName = "", x = 0.521, y = 0.621, mapId = 1454, npcName = "Kaja", },
                { action = 40, questName = "Cooking", x = 0.574, y = 0.539, mapId = 1454, npcName = "Zamja", },
                { class = "z", action = 52, questName = "[Roasted Boar Meat]", npcName = "", notes = "Cook all you have.", amount = "19+", },
                { class = "z", action = 24, questName = "[Recipe: Scorpid Surprise]", npcName = "", },
                { class = "z", action = 42, questName = "", x = 0.572, y = 0.533, mapId = 1454, npcName = "Borstan", },
                { class = "MPrL", action = 40, questName = "Tailoring", x = 0.629, y = 0.492, mapId = 1454, npcName = "Snang", notes = "Note: crafting this wand can be done with significantly less linen. Level up Tailoring to 30 with White Linen Shirt (vendors for 75c), disenchant other greens you have for extra skill, and use the Strange Dust to enchant your bracers to get to 10 Enchanting.", },
                { class = "MPrL", action = 52, questName = "[Bolt of Linen Cloth]", npcName = "", notes = "To 30 tailoring. If you don't have enough linen it's still possible to complete the wand if you have other green items to disenchant instead.", },
                { class = "MPrL", action = 40, questName = "[Brown Linen Robe]", x = 0.629, y = 0.492, mapId = 1454, npcName = "Snang", },
                { class = "MPrL", action = 6, questName = "[Coarse Thread]", x = 0.631, y = 0.515, mapId = 1454, npcName = "Borya", notes = "Up to 9 required to craft wand. May not need all 9.", amount = "9", },
                { class = "MPrL", action = 52, questName = "[Brown Linen Robe]", npcName = "", notes = "May not need all 9 to reach 10 enchanting skill. Each disenchant gives a skill point.", amount = "9", },
                { action = 40, questName = "Weapon Skills", x = 0.817, y = 0.195, mapId = 1454, npcName = "Sayoc", },
                { class = "MPrL", action = 40, questName = "Enchanting", x = 0.535, y = 0.385, mapId = 1454, npcName = "Jhag", },
                { class = "MPrL", action = 6, questName = "[Copper Rod]", x = 0.539, y = 0.380, mapId = 1454, npcName = "Kithas", amount = "1", },
                { class = "MPrL", action = 6, questName = "[Simple Wood]", x = 0.539, y = 0.380, mapId = 1454, npcName = "Kithas", amount = "1", },
                { class = "MPrL", action = 53, questName = "[Brown Linen Robe]", npcName = "", amount = "9", },
                { class = "MPrL", action = 52, questName = "[Runed Copper Rod]", npcName = "", notes = "This gives a skill if you craft it early enough, but you need Lesser Magic Essence which has a 20% chance from the robes, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH.", },
                { class = "MPrL", action = 40, questName = "[Lesser Magic Wand]", x = 0.535, y = 0.385, mapId = 1454, npcName = "Jhag", },
                { class = "MPrL", action = 52, questName = "[Lesser Magic Wand]", npcName = "", notes = "Lesser Magic Essence has a 20% chance from green gear, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH.", },
                { action = 20, questName = "Hidden Enemies", x = 0.316, y = 0.378, mapId = 1454, npcName = "Thrall", questId = 5726, },
                { action = 26, questName = "Hidden Enemies (2)", x = 0.316, y = 0.378, mapId = 1454, npcName = "Thrall", questId = 5727, },
                { action = 20, questName = "Finding the Antidote", x = 0.472, y = 0.536, mapId = 1454, npcName = "Kor'ghan", questId = 813, },
                { class = "L", action = 20, questName = "Creature of the Void", x = 0.483, y = 0.453, mapId = 1454, npcName = "Gan'rul Bloodeye", questId = 1501, },
                { class = "L", action = 26, questName = "The Binding", x = 0.483, y = 0.453, mapId = 1454, npcName = "Gan'rul Bloodeye", questId = 1504, },
                { action = 20, questName = "Neeru Fireblade", x = 0.495, y = 0.506, mapId = 1454, npcName = "Neeru Fireblade", questId = 829, },
                { action = 20, questName = "Burning Shadows", x = 0.495, y = 0.506, mapId = 1454, npcName = "Neeru Fireblade", questId = 832, },
                { action = 26, questName = "Ak'Zeloth", x = 0.495, y = 0.506, mapId = 1454, npcName = "Neeru Fireblade", questId = 809, },
                { action = 7, questName = "Hidden Enemies (2)", x = 0.495, y = 0.506, mapId = 1454, npcName = "Neeru Fireblade", questId = 5727, },
                { action = 26, questName = "Slaying the Beast", x = 0.495, y = 0.506, mapId = 1454, npcName = "Neeru Fireblade", questId = 5761, },
                { class = "L", action = 7, questName = "The Binding", x = 0.494, y = 0.500, mapId = 1454, npcName = ">Summoning Circle<", questId = 1504, },
                { class = "L", action = 20, questName = "The Binding", x = 0.483, y = 0.453, mapId = 1454, npcName = "Gan'rul Bloodeye", questId = 1504, },
                { action = 20, questName = "Hidden Enemies (2)", x = 0.316, y = 0.378, mapId = 1454, npcName = "Thrall", questId = 5727, },
                { action = 26, questName = "Hidden Enemies (3)", x = 0.316, y = 0.378, mapId = 1454, npcName = "Thrall", questId = 5728, },
                { action = 10, questName = "[Lieutenant's Insignia]", npcName = "", },
                { action = 18, questName = "into Ragefire Chasm", x = 0.526, y = 0.492, mapId = 1454, npcName = "", },
                { action = 11, questName = "again", npcName = "", },
                { action = 36, questName = "at Orgrimmar Gates", x = 0.474, y = 0.179, mapId = 1411, npcName = "Spirit Healer", },
                { action = 20, questName = "Need for a Cure", x = 0.415, y = 0.186, mapId = 1411, npcName = "Rhinag", questId = 812, },
                { action = 18, questName = "to Far Watch Post", x = 0.330, y = 0.430, mapId = 1411, npcName = "", },
                { action = 20, questName = "Conscript of the Horde", x = 0.623, y = 0.194, mapId = 1413, npcName = "Kargal Battlescar", questId = 840, },
                { action = 26, questName = "Crossroads Conscription", x = 0.623, y = 0.194, mapId = 1413, npcName = "Kargal Battlescar", questId = 842, },
                { class = "W", action = 20, questName = "Veteran Uzzek", x = 0.614, y = 0.211, mapId = 1413, npcName = "Uzzek", questId = 1505, },
                { class = "W", action = 26, questName = "Path of Defense", x = 0.614, y = 0.211, mapId = 1413, npcName = "Uzzek", questId = 1498, },
                { action = 20, questName = "Ak'Zeloth", x = 0.623, y = 0.201, mapId = 1413, npcName = "Ak'Zeloth", questId = 809, },
                { action = 26, questName = "The Demon Seed", x = 0.623, y = 0.201, mapId = 1413, npcName = "Ak'Zeloth", questId = 924, },
                { class = "DHMPrRL", action = 25, questName = "[Flawed Power Stone]", x = 0.623, y = 0.200, mapId = 1413, npcName = "<Flawed Power Stone>", notes = "Make sure to keep focused! You are now on a 30 minute timer. If you need a break, take it before picking up the stone.", },
                { class = "DHMPrRL", action = 11, questName = "", x = 0.623, y = 0.200, mapId = 1413, npcName = "", notes = "Use the Unstuck feature to die.", },
                { class = "DHMPrRL", action = 36, questName = "at The Crossroads", x = 0.507, y = 0.326, mapId = 1413, npcName = "Spirit Healer", },
                { class = "S", action = 20, questName = "Call of Fire", x = 0.560, y = 0.199, mapId = 1413, npcName = "Kranal Fiss", questId = 1522, },
                { class = "S", action = 26, questName = "Call of Fire (2)", x = 0.560, y = 0.199, mapId = 1413, npcName = "Kranal Fiss", questId = 1524, },
                { class = "S", action = 25, questName = "[Chen's Empty Keg]", x = 0.558, y = 0.200, mapId = 1413, npcName = "<Chen's Empty Keg>", notes = "This is an important rare quest item that spawns througout The Barrens. Keep your eyes peeled for every time Chen's is mentioned in the guide.", },
                { class = "W", action = 7, questName = "Path of Defense", x = 0.390, y = 0.290, mapId = 1411, npcName = "", questId = 1498, },
                { class = "S", action = 18, questName = "up Shaman switchback trail", x = 0.366, y = 0.572, mapId = 1411, npcName = "", },
                { class = "S", action = 20, questName = "Call of Fire (2)", x = 0.386, y = 0.590, mapId = 1411, npcName = "Telf Joolam", questId = 1524, },
                { class = "S", action = 26, questName = "Call of Fire (3)", x = 0.386, y = 0.590, mapId = 1411, npcName = "Telf Joolam", questId = 1525, },
                { class = "S", action = 22, questName = "to Razor Hill", npcName = "", },
                { class = "S", action = 43, questName = "", x = 0.530, y = 0.410, mapId = 1411, npcName = "Ghrawt", },
                { class = "S", action = 7, questName = "Call of Fire (3)", x = 0.528, y = 0.300, mapId = 1411, npcName = "Burning Blade Cultist", questId = 1525, },
                { class = "S", action = 11, questName = "", npcName = "", },
                { class = "S", action = 36, questName = "at Razor Hill", x = 0.535, y = 0.445, mapId = 1411, npcName = "", },
                { class = "S", action = 25, questName = "[Flawed Power Stone]", x = 0.623, y = 0.200, mapId = 1413, npcName = "<Flawed Power Stone>", notes = "Make sure to keep focused! You are now on a 30 minute timer. If you need a break, take it before picking up the stone.", },
                { class = "S", action = 7, questName = "Call of Fire (3)", x = 0.603, y = 0.251, mapId = 1413, npcName = "Razormane Geomancer", questId = 1525, },
                { class = "W", action = 25, questName = "[Flawed Power Stone]", x = 0.623, y = 0.200, mapId = 1413, npcName = "<Flawed Power Stone>", notes = "Make sure to keep focused! You are now on a 30 minute timer. If you need a break, take it before picking up the stone.", },
                { class = "W", action = 20, questName = "Path of Defense", x = 0.614, y = 0.211, mapId = 1413, npcName = "Uzzek", questId = 1498, },
                { class = "W", action = 26, questName = "Thun'grim Firegaze", x = 0.614, y = 0.211, mapId = 1413, npcName = "Uzzek", questId = 1502, },
                { class = "W", action = 18, questName = "up esports footpath", x = 0.601, y = 0.262, mapId = 1413, npcName = "", },
                { class = "W", action = 18, questName = "up Thorn Hill", x = 0.595, y = 0.281, mapId = 1413, npcName = "", notes = "Go up the spine of the mountain and jump over the root.", },
                { class = "W", action = 20, questName = "Thun'grim Firegaze", x = 0.572, y = 0.303, mapId = 1413, npcName = "Thun'grim Firegaze", questId = 1502, },
                { class = "W", action = 26, questName = "Forged Steel", x = 0.572, y = 0.303, mapId = 1413, npcName = "Thun'grim Firegaze", questId = 1503, },
                { class = "W", action = 7, questName = "Forged Steel", x = 0.550, y = 0.267, mapId = 1413, npcName = "<Stolen Iron Chest>", questId = 1503, notes = "If you already have a good weapon you can do this quest later, while you do Disrupt the Attacks.", },
                { class = "W", action = 20, questName = "Forged Steel", x = 0.550, y = 0.267, mapId = 1413, npcName = "Thun'grim Firegaze", questId = 1503, },
                { class = "S", action = 18, questName = "up Shaman switchback trail", x = 0.366, y = 0.572, mapId = 1411, npcName = "", notes = "Follow path marked with a Shaman class stone", },
                { class = "S", action = 20, questName = "Call of Fire (3)", x = 0.386, y = 0.590, mapId = 1411, npcName = "Telf Joolam", questId = 1525, },
                { class = "S", action = 26, questName = "Call of Fire (4)", x = 0.386, y = 0.590, mapId = 1411, npcName = "Telf Joolam", questId = 1526, },
                { class = "S", action = 41, questName = "[Fire Sapta]", x = 0.381, y = 0.585, mapId = 1411, npcName = ">Shaman Shrine<", notes = "You have to use it near the Shaman Shrine stone.", },
                { class = "S", action = 7, questName = "Call of Fire (4)", x = 0.388, y = 0.522, mapId = 1411, npcName = "Minor Manifestation of Fire", questId = 1526, },
                { class = "S", action = 20, questName = "Call of Fire (4)", x = 0.390, y = 0.582, mapId = 1411, npcName = "<Brazier of the Dormant Flame>", questId = 1526, },
                { class = "S", action = 26, questName = "Call of Fire (5)", x = 0.390, y = 0.582, mapId = 1411, npcName = "<Brazier of the Dormant Flame>", questId = 1527, },
                { class = "S", action = 18, questName = "to The Barrens", x = 0.354, y = 0.587, mapId = 1411, npcName = "", },
                { class = "S", action = 11, questName = "in The Barrens", x = 0.630, y = 0.280, mapId = 1413, npcName = "", },
                { class = "S", action = 36, questName = "at The Crossroads", x = 0.507, y = 0.326, mapId = 1413, npcName = "Spirit Healer", },
                { action = 26, questName = "The Forgotten Pools", x = 0.523, y = 0.319, mapId = 1413, npcName = "Tonga Runetotem", questId = 870, },
                { action = 42, questName = "", x = 0.523, y = 0.319, mapId = 1413, npcName = "Halija Whitestrider", },
                { action = 20, questName = "Crossroads Conscription", x = 0.522, y = 0.310, mapId = 1413, npcName = "Sergra Darkthorn", questId = 842, },
                { action = 26, questName = "Plainstrider Menace", x = 0.522, y = 0.310, mapId = 1413, npcName = "Sergra Darkthorn", questId = 844, },
                { action = 33, questName = "at The Crossroads", x = 0.520, y = 0.299, mapId = 1413, npcName = "Innkeeper Boorand", },
                { action = 26, questName = "Raptor Thieves", x = 0.519, y = 0.303, mapId = 1413, npcName = "Gazrog", questId = 869, },
                { action = 26, questName = "Disrupt the Attacks", x = 0.515, y = 0.309, mapId = 1413, npcName = "Thork", questId = 871, },
                { action = 26, questName = "Supplies for the Crossroads", x = 0.515, y = 0.309, mapId = 1413, npcName = "Thork", questId = 5041, },
                { action = 17, questName = "at The Crossroads", x = 0.515, y = 0.303, mapId = 1413, npcName = "Devrak", },
                { action = 26, questName = "Fungal Spores", x = 0.514, y = 0.302, mapId = 1413, npcName = "Apothecary Helbrim", questId = 848, },
                { action = 26, questName = "Wharfmaster Dizzywig", x = 0.514, y = 0.302, mapId = 1413, npcName = "Apothecary Helbrim", questId = 1492, },
                { action = 42, questName = "", x = 0.517, y = 0.300, mapId = 1413, npcName = "Tari'qa", },
                { action = 29, questName = "Plainstrider Menace", x = 0.490, y = 0.290, mapId = 1413, npcName = "", questId = 844, },
                { action = 26, questName = "Kolkar Leaders", x = 0.454, y = 0.284, mapId = 1413, npcName = "Regthar Deathgate", questId = 850, },
                { action = 26, questName = "Centaur Bracers", x = 0.454, y = 0.284, mapId = 1413, npcName = "Regthar Deathgate", questId = 855, },
                { action = 29, questName = "Centaur Bracers", x = 0.455, y = 0.255, mapId = 1413, npcName = "", questId = 855, },
                { action = 8, questName = "Fungal Spores", x = 0.450, y = 0.220, mapId = 1413, npcName = "<Laden Mushroom>", questId = 848, },
                { action = 8, questName = "The Forgotten Pools", x = 0.451, y = 0.225, mapId = 1413, npcName = "", questId = 870, notes = "Groups of 2 or more should loot all mushrooms at the oasis, then complete The Demon Seed, then come back down and get the rest of the mushrooms afterward.", },
                { action = 18, questName = "up Dreadmist Peak", x = 0.470, y = 0.205, mapId = 1413, npcName = "", },
                { action = 8, questName = "The Demon Seed", x = 0.480, y = 0.191, mapId = 1413, npcName = "", questId = 924, notes = "If Rathorian (level 15 rare) is there, you can use your [Really Sticky Glue] to root him in place while you complete the objective (by clicking the altar).", },
                { action = 29, questName = "Plainstrider Menace", x = 0.490, y = 0.200, mapId = 1413, npcName = "", questId = 844, },
                { class = "S", action = 25, questName = "[Chen's Empty Keg]", x = 0.558, y = 0.200, mapId = 1413, npcName = "<Chen's Empty Keg>", },
                { class = "S", action = 20, questName = "Call of Fire (5)", x = 0.560, y = 0.199, mapId = 1413, npcName = "Kranal Fiss", questId = 1527, },
                { action = 8, questName = "Plainstrider Menace", x = 0.520, y = 0.230, mapId = 1413, npcName = "", questId = 844, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end