local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "orc" then
    LiveGuide.registerLevel({
        guide = "LiveGuideOrc",
        race = "orc",
        title = "33-34",
        level = 33,
        nextLevel = 34,
        steps = function()
            return {
                { class = "W", action = 18, questName = "to Alterac Mountains", x = 0.705, y = 0.098, mapId = 1424, npcName = "", },
                { class = "DHMPrRSL", action = 18, questName = "to Alterac Mountains", x = 0.553, y = 0.098, mapId = 1424, npcName = "", },
                { class = "W", action = 20, questName = "The Windwatcher", x = 0.805, y = 0.669, mapId = 1416, npcName = "Bath'rah the Windwatcher", questId = 1791, notes = "There be dragons.", },
                { class = "W", action = 26, questName = "Cyclonian", x = 0.805, y = 0.669, mapId = 1416, npcName = "Bath'rah the Windwatcher", questId = 1712, },
                { class = "W", action = 10, questName = "[Bath'rah's Parchment]", npcName = "", },
                { action = 26, questName = "Valik", x = 0.572, y = 0.695, mapId = 1416, npcName = "Henchman Valik", questId = 535, },
                { action = 8, questName = "Valik", x = 0.580, y = 0.680, mapId = 1416, npcName = "Drunken Footpad", questId = 535, },
                { action = 20, questName = "Valik", x = 0.572, y = 0.695, mapId = 1416, npcName = "Henchman Valik", questId = 535, },
                { action = 8, questName = "Infiltration", x = 0.580, y = 0.670, mapId = 1416, npcName = "", questId = 533, },
                { class = "z", action = 19, questName = "[Lion Meat]", x = 0.320, y = 0.840, mapId = 1416, npcName = "", notes = "Save for Cooking. Bring with you to Desolace in a bit.", amount = "25", },
                { action = 25, questName = "[Fresh Carcass]", x = 0.460, y = 0.780, mapId = 1416, npcName = "", notes = "Looted from any mountain lion. You might not be able to solo this quest. Try and see if you can. If you can't, don't worry, we'll be back later.", },
                { action = 18, questName = "to Growless Cave", x = 0.406, y = 0.741, mapId = 1416, npcName = "", notes = "Avoid aggroing the Alliance AV guards.", },
                { action = 7, questName = "Helcular's Revenge (2)", x = 0.375, y = 0.662, mapId = 1416, npcName = "<Flame of Uzel>", questId = 553, },
                { action = 8, questName = "Frostmaw", x = 0.375, y = 0.662, mapId = 1416, npcName = "Frostmaw", questId = 1136, notes = "If you can't do it now, we'll be back later.", },
                { action = 18, questName = "around Ruins of Alterac", x = 0.320, y = 0.670, mapId = 1416, npcName = "", notes = "This trip is optional. We are going to try to buy a rare recipe from a hidden vendor: [Recipe: Frost Oil]. The recipe is not necessary but is valuable. Additionally, you will need 1 [Frost Oil] later on so having the recipe may come in handy.", },
                { action = 18, questName = "to castle wall", x = 0.359, y = 0.400, mapId = 1416, npcName = "", notes = "Follow the trail of Giant Yetis around the outside of the snowy area past Growless cave.", },
                { action = 23, questName = "onto ledge", x = 0.368, y = 0.409, mapId = 1416, npcName = "", notes = "This requires a bit of tricky climbing. You can skip this entire step if you don't want the chance at [Recipe: Frost Oil]. Facing the wall, climb up the far right corner.", },
                { action = 23, questName = "onto other ledge", x = 0.369, y = 0.407, mapId = 1416, npcName = "", notes = "Once you're on the wall's ledge, jump onto the main section of the wall by jumping against the wall and sliding onto the next ledge.", },
                { action = 23, questName = "around pillar", x = 0.371, y = 0.407, mapId = 1416, npcName = "", notes = "Jumping against the wall allows you to slide past the obstacle. Alternatively you can try to carefully walk around it.", },
                { action = 18, questName = "through crack in wall", x = 0.376, y = 0.399, mapId = 1416, npcName = "", },
                { action = 18, questName = "past elite mob", x = 0.386, y = 0.401, mapId = 1416, npcName = "Crushridge Mage", notes = "Use any CC you have. Get past him, climb the wall, talk to the vendor, buy his stuff, and jump off the wall to safety.", },
                { action = 18, questName = "up ramp", x = 0.388, y = 0.394, mapId = 1416, npcName = "", },
                { action = 6, questName = "[Recipe: Frost Oil]", x = 0.382, y = 0.389, mapId = 1416, npcName = "Bro'kin", notes = "There is a limited stock. Also buy Greater Healing Potions and maybe Mana Potions. You will want someone to make Frost Oil for you later (for a Badlands quest). It doesn't hurt to have the recipe in case you find a 200 Alchemist without it. Or you could just sell the recipe on the AH. *rubs fingers*", },
                { action = 18, questName = "to Dalaran", x = 0.310, y = 0.720, mapId = 1416, npcName = "", },
                { action = 7, questName = "Prison Break In", x = 0.202, y = 0.843, mapId = 1416, npcName = "Ricter", questId = 544, },
                { action = 7, questName = "Prison Break In", x = 0.204, y = 0.864, mapId = 1416, npcName = "Alina", questId = 544, },
                { action = 7, questName = "Prison Break In", x = 0.199, y = 0.862, mapId = 1416, npcName = "Dermot", questId = 544, },
                { action = 8, questName = "Prison Break In", x = 0.178, y = 0.832, mapId = 1416, npcName = "Kegan Darkmar", questId = 544, },
                { action = 8, questName = "Stone Tokens", x = 0.200, y = 0.830, mapId = 1416, npcName = "", questId = 556, },
                { action = 18, questName = "to Hillsbrad Foothills", x = 0.286, y = 0.924, mapId = 1416, npcName = "", },
                { action = 38, questName = "for Dun Garok elite quests", npcName = "", notes = "Skip them if you can't find a group.", },
                { action = 7, questName = "Helcular's Revenge (2)", x = 0.439, y = 0.281, mapId = 1424, npcName = "<Flame of Azel>", questId = 553, notes = "Two flames in this cave; one up, one down.", },
                { action = 8, questName = "Helcular's Revenge (2)", x = 0.440, y = 0.265, mapId = 1424, npcName = "<Flame of Veraz>", questId = 553, notes = "Two flames in this cave; one up, one down.", },
                { action = 20, questName = "Helcular's Revenge (2)", x = 0.528, y = 0.534, mapId = 1424, npcName = "<Helcular's Grave>", questId = 553, },
                { action = 18, questName = "to Tarren Mill", x = 0.616, y = 0.209, mapId = 1424, npcName = "", },
                { action = 20, questName = "Prison Break In", x = 0.616, y = 0.209, mapId = 1424, npcName = "Magus Wordeen Voidglare", questId = 544, },
                { action = 35, questName = "Dalaran Patrols", x = 0.616, y = 0.209, mapId = 1424, npcName = "Magus Wordeen Voidglare", questId = 545, },
                { action = 20, questName = "Stone Tokens", x = 0.615, y = 0.209, mapId = 1424, npcName = "Keeper Bel'varil", questId = 556, },
                { action = 35, questName = "Bracers of Binding", x = 0.615, y = 0.209, mapId = 1424, npcName = "Keeper Bel'varil", questId = 557, },
                { action = 20, questName = "Infiltration", x = 0.632, y = 0.207, mapId = 1424, npcName = "Krusk", questId = 533, },
                { action = 35, questName = "Gol'dir", x = 0.632, y = 0.207, mapId = 1424, npcName = "Krusk", questId = 503, },
                { action = 26, questName = "Humbert's Sword", x = 0.628, y = 0.202, mapId = 1424, npcName = "Deathguard Humbert", questId = 547, },
                { action = 18, questName = "to Dun Garok", x = 0.700, y = 0.770, mapId = 1424, npcName = "", },
                { action = 8, questName = "Humbert's Sword", x = 0.700, y = 0.770, mapId = 1424, npcName = "", questId = 547, },
                { action = 8, questName = "Elixir of Agony (4)", x = 0.716, y = 0.810, mapId = 1424, npcName = "", questId = 517, notes = "You'll need a group.", },
                { action = 8, questName = "Battle of Hillsbrad (6)", x = 0.711, y = 0.803, mapId = 1424, npcName = "", questId = 541, },
                { action = 20, questName = "Battle of Hillsbrad (6)", x = 0.623, y = 0.205, mapId = 1424, npcName = "High Executor Darthalia", questId = 541, },
                { action = 26, questName = "Battle of Hillsbrad (7)", x = 0.623, y = 0.205, mapId = 1424, npcName = "High Executor Darthalia", questId = 550, },
                { action = 20, questName = "Humbert's Sword", x = 0.628, y = 0.202, mapId = 1424, npcName = "Deathguard Humbert", questId = 547, },
                { action = 20, questName = "Elixir of Agony (4)", x = 0.614, y = 0.191, mapId = 1424, npcName = "Apothecary Lydon", questId = 517, },
                { action = 26, questName = "Elixir of Agony (4)", x = 0.614, y = 0.191, mapId = 1424, npcName = "Apothecary Lydon", questId = 524, },
                { action = 20, questName = "Elixir of Agony (4)", x = 0.628, y = 0.187, mapId = 1424, npcName = "<Dusty Rug>", questId = 524, },
                { action = 18, questName = "to Arathi Highlands", x = 0.819, y = 0.569, mapId = 1424, npcName = "", },
                { action = 18, questName = "to Arathi Highlands", x = 0.211, y = 0.309, mapId = 1417, npcName = "", },
                { action = 8, questName = "The Hammer May Fall", x = 0.347, y = 0.441, mapId = 1417, npcName = "", questId = 676, },
                { action = 18, questName = "to Hammerfall", x = 0.746, y = 0.380, mapId = 1417, npcName = "", },
                { action = 26, questName = "Foul Magics", x = 0.747, y = 0.363, mapId = 1417, npcName = "Tor'gan", questId = 671, },
                { action = 26, questName = "Hammerfall", x = 0.728, y = 0.342, mapId = 1417, npcName = "Gor'mul", questId = 655, },
                { action = 42, questName = "", x = 0.725, y = 0.334, mapId = 1417, npcName = "Mu'uta", },
                { action = 31, questName = "", x = 0.725, y = 0.334, mapId = 1417, npcName = "Mu'uta", },
                { class = "H", action = 37, questName = "", x = 0.739, y = 0.331, mapId = 1417, npcName = "Tharlidun", },
                { action = 20, questName = "The Hammer May Fall", x = 0.742, y = 0.339, mapId = 1417, npcName = "Drum Fel", questId = 676, },
                { action = 26, questName = "Call to Arms", x = 0.742, y = 0.339, mapId = 1417, npcName = "Drum Fel", questId = 677, },
                { action = 17, questName = "at Hammerfall", x = 0.731, y = 0.327, mapId = 1417, npcName = "Urda", },
                { action = 20, questName = "Hammerfall", x = 0.747, y = 0.363, mapId = 1417, npcName = "Tor'gan", questId = 655, },
                { action = 26, questName = "Raising Spirits", x = 0.747, y = 0.363, mapId = 1417, npcName = "Tor'gan", questId = 672, },
                { class = "H", action = 39, questName = "", x = 0.680, y = 0.390, mapId = 1417, npcName = "Young Mesa Buzzard", },
                { class = "H", action = 29, questName = "Raising Spirits", x = 0.680, y = 0.390, mapId = 1417, npcName = "", questId = 672, },
                { class = "H", action = 24, questName = "Dive (Rank 1)", x = 0.680, y = 0.390, mapId = 1417, npcName = "", },
                { class = "H", action = 1, questName = "", x = 0.680, y = 0.390, mapId = 1417, npcName = "Young Mesa Buzzard", },
                { class = "H", action = 44, questName = "", x = 0.739, y = 0.331, mapId = 1417, npcName = "Tharlidun", },
                { action = 29, questName = "Raising Spirits", x = 0.680, y = 0.400, mapId = 1417, npcName = "", questId = 672, },
                { action = 8, questName = "To Steal From Thieves", x = 0.550, y = 0.380, mapId = 1417, npcName = "", questId = 1164, },
                { action = 8, questName = "Raising Spirits", x = 0.430, y = 0.400, mapId = 1417, npcName = "", questId = 672, },
                { action = 8, questName = "Foul Magics", x = 0.320, y = 0.280, mapId = 1417, npcName = "", questId = 671, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end