local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "troll" then
    LiveGuide.registerLevel({
        guide = "LiveGuideTroll",
        race = "troll",
        title = "23-24",
        level = 23,
        nextLevel = 24,
        steps = function()
            return {
                { action = 8, questName = "Gann's Reclamation", x = 0.483, y = 0.862, mapId = 1413, npcName = "Prospector Khazgorm", questId = 843, },
                { action = 20, questName = "Gann's Reclamation", x = 0.460, y = 0.770, mapId = 1413, npcName = "Gann Stonespire", questId = 843, },
                { action = 26, questName = "Revenge of Gann", x = 0.460, y = 0.770, mapId = 1413, npcName = "Gann Stonespire", questId = 846, },
                { action = 18, questName = "to Camp Taurajo", x = 0.445, y = 0.593, mapId = 1413, npcName = "", },
                { action = 20, questName = "Betrayal from Within", x = 0.445, y = 0.593, mapId = 1413, npcName = "Mangletooth", questId = 879, },
                { action = 26, questName = "Betrayal from Within (2)", x = 0.445, y = 0.593, mapId = 1413, npcName = "Mangletooth", questId = 906, },
                { action = 2, questName = "Washte Pawne", npcName = "[Washte Pawne's Feather]", questId = 885, notes = "The icon for this item is a feather.", },
                { action = 2, questName = "Owatanka", npcName = "[Owatanka's Tailspike]", questId = 884, },
                { action = 20, questName = "Washte Pawne", x = 0.449, y = 0.591, mapId = 1413, npcName = "Jorn Skyseer", questId = 885, notes = "Buffs you with +2 Spirit.", },
                { action = 20, questName = "Owatanka", x = 0.449, y = 0.591, mapId = 1413, npcName = "Jorn Skyseer", questId = 884, notes = "Buffs you with +2 Spirit.", },
                { action = 20, questName = "Cry of the Thunderhawk", x = 0.449, y = 0.591, mapId = 1413, npcName = "Jorn Skyseer", questId = 913, },
                { action = 26, questName = "Mahren Skyseer", x = 0.449, y = 0.591, mapId = 1413, npcName = "Jorn Skyseer", questId = 874, },
                { action = 43, questName = "", x = 0.451, y = 0.590, mapId = 1413, npcName = "Sanuye Runetotem", notes = "Don't vendor the quest items!", },
                { action = 20, questName = "Weapons of Choice", x = 0.451, y = 0.577, mapId = 1413, npcName = "Tatternack Steelforge", questId = 893, },
                { class = "R", action = 16, questName = "to The Crossroads", x = 0.444, y = 0.592, mapId = 1413, npcName = "Omusa Thunderhorn", notes = "30+ min deviation", },
                { class = "DHMPrSLW", action = 16, questName = "to Ratchet", x = 0.444, y = 0.592, mapId = 1413, npcName = "Omusa Thunderhorn", },
                { class = "R", action = 8, questName = "Deep Cover", x = 0.554, y = 0.056, mapId = 1413, npcName = "Taskmaster Fizzule", questId = 2458, notes = "Just outside aggro range, fire the flare gun twice and then /salute him.", },
                { class = "R", action = 20, questName = "Deep Cover", x = 0.554, y = 0.056, mapId = 1413, npcName = "Taskmaster Fizzule", questId = 2458, },
                { class = "R", action = 26, questName = "Mission: Possible But Not Probable", x = 0.554, y = 0.056, mapId = 1413, npcName = "Taskmaster Fizzule", questId = 2478, },
                { class = "R", action = 50, questName = "[Silixiz's Tower Key]", x = 0.548, y = 0.060, mapId = 1413, npcName = "Foreman Silixiz", notes = "If his pick pocket loot is empty, kill him and pick pocket him when he respawns.", },
                { class = "R", action = 7, questName = "Mission: Possible But Not Probable", x = 0.547, y = 0.058, mapId = 1413, npcName = "Mutated Venture Co. Drone", questId = 2478, notes = "First floor. Ambush instakills them. Helps to ambush one, run away, come back and ambush the other. Have to clear a path to run away though.", },
                { class = "R", action = 7, questName = "Mission: Possible But Not Probable", x = 0.547, y = 0.058, mapId = 1413, npcName = "Venture Co. Patroller", questId = 2478, notes = "Second floor. Weak to rupture. Two 1 point ruptures back to back will kill them.", },
                { class = "R", action = 7, questName = "Mission: Possible But Not Probable", x = 0.547, y = 0.058, mapId = 1413, npcName = "Venture Co. Lookout", questId = 2478, notes = "Third floor. Weak to eviscerate. 1 pointers are sufficient.", },
                { class = "R", action = 7, questName = "Mission: Possible But Not Probable", x = 0.548, y = 0.056, mapId = 1413, npcName = "Grand Foreman Puzik Gallywix", questId = 2478, notes = "Top floor. Weak to ambush. Ambush --> Vanish --> Ambush before he ticks back to full, then evasion and FINISH HIM.", },
                { class = "R", action = 8, questName = "Mission: Possible But Not Probable", x = 0.548, y = 0.056, mapId = 1413, npcName = "<Gallywix's Lockbox>", questId = 2478, notes = "Need at least 80 Lockpicking (confirm this in beta)", },
                { class = "R", action = 51, questName = "", x = 0.548, y = 0.056, mapId = 1413, npcName = "<Gallywix's Lockbox>", notes = "Until max lockpicking or at least until gallywix respawns. You will need to come back and skill up to 175 on this chest later.", },
                { action = 20, questName = "Chen's Empty Keg (3)", x = 0.623, y = 0.384, mapId = 1413, npcName = "Brewmaster Drohn", questId = 822, },
                { action = 20, questName = "Mahren Skyseer", x = 0.658, y = 0.439, mapId = 1413, npcName = "Mahren Skyseer", questId = 874, },
                { action = 26, questName = "Isha Awak", x = 0.658, y = 0.439, mapId = 1413, npcName = "Mahren Skyseer", questId = 873, },
                { action = 8, questName = "Isha Awak", x = 0.635, y = 0.539, mapId = 1413, npcName = "Isha Awak", questId = 873, notes = "Pats up and down the coast from the questgiver down to Northwatch Hold.", },
                { action = 20, questName = "Isha Awak", x = 0.658, y = 0.439, mapId = 1413, npcName = "Mahren Skyseer", questId = 873, },
                { action = 22, questName = "to Sun Rock Retreat", npcName = "", },
                { action = 42, questName = "", x = 0.475, y = 0.621, mapId = 1442, npcName = "Innkeeper Jayka", },
                { action = 20, questName = "Earthen Arise", x = 0.472, y = 0.640, mapId = 1442, npcName = "Mor'rogal", questId = 6481, },
                { action = 26, questName = "Trouble in the Deeps", x = 0.473, y = 0.644, mapId = 1442, npcName = "Tsunaman", questId = 6562, },
                { action = 26, questName = "Elemental War", x = 0.473, y = 0.644, mapId = 1442, npcName = "Tsunaman", questId = 6393, },
                { action = 8, questName = "Gerenzo Wrenchwhistle", x = 0.645, y = 0.403, mapId = 1442, npcName = "Gerenzo Wrenchwhistle", questId = 1096, },
                { action = 18, questName = "to The Talondeep Path", x = 0.783, y = 0.427, mapId = 1442, npcName = "", },
                { action = 18, questName = "through The Talondeep Path", x = 0.422, y = 0.713, mapId = 1440, npcName = "", },
                { action = 18, questName = "around Astranaar", x = 0.335, y = 0.594, mapId = 1440, npcName = "", },
                { action = 18, questName = "past Maestra's Post", x = 0.244, y = 0.377, mapId = 1440, npcName = "", },
                { action = 18, questName = "to Zoram'gar Outpost", x = 0.120, y = 0.340, mapId = 1440, npcName = "", },
                { action = 17, questName = "at Zoram'gar Outpost", x = 0.122, y = 0.338, mapId = 1440, npcName = "Andruk", },
                { action = 7, questName = "The Warsong Reports", x = 0.122, y = 0.342, mapId = 1440, npcName = "Warsong Runner", questId = 6543, },
                { action = 42, questName = "", x = 0.117, y = 0.341, mapId = 1440, npcName = "Wik'Tar", },
                { action = 20, questName = "Trouble in the Deeps", x = 0.116, y = 0.343, mapId = 1440, npcName = "Je'neu Sancrea", questId = 6394, },
                { action = 34, questName = "The Essence of Aku'Mai", x = 0.116, y = 0.343, mapId = 1440, npcName = "Je'neu Sancrea", questId = 6563, },
                { action = 26, questName = "Between a Rock and a Thistlefur", x = 0.119, y = 0.345, mapId = 1440, npcName = "Karang Amakkar", questId = 216, },
                { action = 26, questName = "Troll Charm", x = 0.116, y = 0.349, mapId = 1440, npcName = "Mitsuwa", questId = 6462, },
                { action = 26, questName = "Naga at the Zoram Strand", x = 0.117, y = 0.349, mapId = 1440, npcName = "Marukai", questId = 6442, notes = "The quest ! may not show up over the NPC.", },
                { action = 26, questName = "Vorsha the Lasher", x = 0.121, y = 0.346, mapId = 1440, npcName = "Muglash", questId = 6641, notes = "If he's not up, grind naga nearby for heads until he spawns. Good mobs to gind. GROUP UP with other people waiting to do the quest! Worth waiting for.", },
                { action = 8, questName = "Vorsha the Lasher", x = 0.096, y = 0.276, mapId = 1440, npcName = "<Naga Brazier>", questId = 6641, },
                { action = 8, questName = "Naga at the Zoram Strand", x = 0.120, y = 0.290, mapId = 1440, npcName = "", questId = 6442, notes = "If you have a group, I recommend going into BFD at this point and farming the Blackfathom Tide Priestesses until the [Damp Note] drops. Doing this now will net you an additional BFD quest with good rewards.", },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end