local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "troll" then
    LiveGuide.registerLevel({
        guide = "LiveGuideTroll",
        race = "troll",
        title = "27-28",
        level = 27,
        nextLevel = 28,
        steps = function()
            return {
                { action = 20, questName = "Elemental War", x = 0.473, y = 0.644, mapId = 1442, npcName = "Tsunaman", questId = 6393, },
                { action = 20, questName = "Harpies Threaten", x = 0.472, y = 0.611, mapId = 1442, npcName = "Maggran Earthbinder", questId = 6282, },
                { action = 26, questName = "Bloodfury Bloodline", x = 0.472, y = 0.611, mapId = 1442, npcName = "Maggran Earthbinder", questId = 6283, },
                { action = 20, questName = "New Life", x = 0.475, y = 0.584, mapId = 1442, npcName = "Tammra Windfield", questId = 6381, },
                { action = 43, questName = "", x = 0.454, y = 0.591, mapId = 1442, npcName = "Borand", },
                { action = 16, questName = "to Thunder Bluff", x = 0.451, y = 0.598, mapId = 1442, npcName = "Tharm", notes = "Rogues: if you want cheap shot, fly to Orgrimmar to train.", },
                { class = "DHRSW", action = 20, questName = "Blackfathom Villainy", x = 0.711, y = 0.342, mapId = 1456, npcName = "Bashana Runetotem", questId = 6561, },
                { class = "D", action = 40, questName = "", x = 0.765, y = 0.272, mapId = 1456, npcName = "Turak Runetotem", },
                { class = "D", action = 20, questName = "Aquatic Form", x = 0.765, y = 0.272, mapId = 1456, npcName = "Turak Runetotem", questId = 31, },
                { class = "H", action = 40, questName = "", x = 0.661, y = 0.185, mapId = 1456, npcName = "Ormak Grimshot", },
                { class = "M", action = 40, questName = "", x = 0.257, y = 0.142, mapId = 1456, npcName = "Ursyn Ghull", },
                { class = "Pr", action = 40, questName = "", x = 0.245, y = 0.226, mapId = 1456, npcName = "Malakai Cross", },
                { class = "S", action = 40, questName = "", x = 0.388, y = 0.364, mapId = 1456, npcName = "Kardris Dreamseeker", },
                { class = "W", action = 40, questName = "", x = 0.798, y = 0.314, mapId = 1456, npcName = "Grezz Ragefist", },
                { action = 20, questName = "Return to Thunder Bluff", x = 0.228, y = 0.209, mapId = 1456, npcName = "Apothecary Zamah", questId = 1067, },
                { action = 26, questName = "The Flying Machine Airport", x = 0.228, y = 0.209, mapId = 1456, npcName = "Apothecary Zamah", questId = 1086, },
                { class = "M", action = 54, questName = "to Orgrimmar", x = 0.228, y = 0.209, mapId = 1456, npcName = "", },
                { class = "S", action = 16, questName = "to Camp Taurajo", x = 0.470, y = 0.498, mapId = 1456, npcName = "Tal", },
                { class = "DHPrRLW", action = 22, questName = "to Sun Rock Retreat", x = 0.228, y = 0.209, mapId = 1456, npcName = "", },
                { class = "S", action = 20, questName = "Call of Water (4)", x = 0.745, y = 0.977, mapId = 1413, npcName = "Brine", questId = 1536, },
                { class = "S", action = 26, questName = "Call of Water (5)", x = 0.745, y = 0.977, mapId = 1413, npcName = "Brine", questId = 1534, },
                { class = "S", action = 22, questName = "to Sun Rock Retreat", npcName = "", },
                { class = "M", action = 20, questName = "Speak with Deino", x = 0.384, y = 0.861, mapId = 1454, npcName = "Deino", questId = 1943, },
                { class = "M", action = 26, questName = "Waters of Xavian", x = 0.384, y = 0.861, mapId = 1454, npcName = "Deino", questId = 1944, },
                { class = "M", action = 16, questName = "to Splintertree Post", x = 0.451, y = 0.639, mapId = 1454, npcName = "Doras", },
                { class = "M", action = 8, questName = "Waters of Xavian", x = 0.763, y = 0.415, mapId = 1440, npcName = ">Xavian Waterfall<", questId = 1944, notes = "River path (right exiting Splintertree) for saftey. Forest path (left exiting Splitertree) for speed.", },
                { class = "M", action = 54, questName = "to Orgrimmar", npcName = "", },
                { class = "M", action = 20, questName = "Waters of Xavian", x = 0.384, y = 0.861, mapId = 1454, npcName = "Deino", questId = 1944, },
                { class = "M", action = 26, questName = "Laughing Sisters", x = 0.384, y = 0.861, mapId = 1454, npcName = "Deino", questId = 1945, },
                { class = "M", action = 22, questName = "to Sun Rock Retreat", npcName = "", },
                { action = 8, questName = "Bloodfury Bloodline", x = 0.307, y = 0.619, mapId = 1442, npcName = "Bloodfury Ripper", questId = 6283, notes = "Can't solo, grind mobs around her until someone comes by and party with them. If no one comes just grind the xp you would have gotten from the quest.", },
                { action = 19, questName = "to 20000 / 38900 L27", x = 0.370, y = 0.510, mapId = 1442, npcName = "", notes = "Grind another 2k if you didn't complete Bloodfury Bloodline.", },
                { action = 20, questName = "Bloodfury Bloodline", x = 0.472, y = 0.611, mapId = 1442, npcName = "Maggran Earthbinder", questId = 6283, },
                { action = 43, questName = "", x = 0.454, y = 0.591, mapId = 1442, npcName = "Borand", },
                { action = 20, questName = "Gerenzo Wrenchwhistle", x = 0.590, y = 0.626, mapId = 1442, npcName = "Ziz Fizziks", questId = 1096, },
                { action = 8, questName = "The Flying Machine Airport", x = 0.665, y = 0.454, mapId = 1442, npcName = ">Venture Co. Copter Pad<", questId = 1086, },
                { action = 18, questName = "to The Talondeep Path", x = 0.783, y = 0.427, mapId = 1442, npcName = "", },
                { action = 18, questName = "through The Talondeep Path", x = 0.422, y = 0.713, mapId = 1440, npcName = "", },
                { action = 25, questName = "[Ursangous's Paw]", x = 0.420, y = 0.680, mapId = 1440, npcName = "Ursangous", notes = "If he's not up, grind while you wait.", },
                { class = "S", action = 8, questName = "Call of Water (5)", x = 0.335, y = 0.675, mapId = 1440, npcName = ">Ruins of Stardust Fountain<", questId = 1534, },
                { action = 8, questName = "Stonetalon Standstill", x = 0.489, y = 0.696, mapId = 1440, npcName = "", questId = 25, },
                { action = 25, questName = "[Befouled Water Globe]", x = 0.487, y = 0.706, mapId = 1440, npcName = "Tideress", notes = "If he's not up, grind while you wait.", },
                { action = 8, questName = "King of the Foulweald", x = 0.564, y = 0.635, mapId = 1440, npcName = ">Foulweald Totem Mound<", questId = 6621, notes = "Very hard; skip if solo. Mobs come in waves constantly before Chief Murgut spawns.", },
                { action = 25, questName = "[Shadumbra's Head]", x = 0.550, y = 0.550, mapId = 1440, npcName = "Shadumbra", notes = "Grind Laughing Sisters if not up.", },
                { action = 25, questName = "[Etched Phial]", x = 0.590, y = 0.560, mapId = 1440, npcName = "Laughing Sister", },
                { class = "M", action = 8, questName = "Laughing Sisters", x = 0.590, y = 0.560, mapId = 1440, npcName = "Laughing Sister", questId = 1945, },
                { action = 8, questName = "Ordanus", x = 0.621, y = 0.514, mapId = 1440, npcName = "Keeper Ordanus", questId = 1088, notes = "Line of Sight his casts. can solo but hard. If too hard then just grind another 2400 xp on Laughing Sisters.", },
                { action = 8, questName = "The Sacred Flame", x = 0.602, y = 0.729, mapId = 1440, npcName = ">Ashenvale Moonwell<", questId = 1195, },
                { action = 45, questName = "[Sharptalon's Claw]", x = 0.750, y = 0.700, mapId = 1440, npcName = "Sharptalon", },
                { action = 2, questName = "Ursangous's Paw", npcName = "[Ursangous's Paw]", questId = 23, },
                { action = 20, questName = "Ursangous's Paw", x = 0.738, y = 0.615, mapId = 1440, npcName = "Senani Thunderheart", questId = 23, },
                { action = 2, questName = "Shadumbra's Head", npcName = "[Shadumbra's Head]", questId = 24, },
                { action = 20, questName = "Shadumbra's Head", x = 0.738, y = 0.615, mapId = 1440, npcName = "Senani Thunderheart", questId = 24, },
                { action = 46, questName = "Sharptalon's Claw", npcName = "[Sharptalon's Claw]", questId = 2, notes = "If you didn't did it already.", },
                { action = 21, questName = "Sharptalon's Claw", x = 0.738, y = 0.615, mapId = 1440, npcName = "Senani Thunderheart", questId = 2, },
                { action = 30, questName = "The Hunt Completed", x = 0.738, y = 0.615, mapId = 1440, npcName = "Senani Thunderheart", questId = 247, },
                { action = 43, questName = "", x = 0.735, y = 0.603, mapId = 1440, npcName = "Burkrum", },
                { action = 2, questName = "The Befouled Element", npcName = "[Befouled Water Globe]", questId = 1918, },
                { action = 20, questName = "Stonetalon Standstill", x = 0.737, y = 0.600, mapId = 1440, npcName = "Mastok Wrilehiss", questId = 25, },
                { action = 20, questName = "The Befouled Element", x = 0.737, y = 0.600, mapId = 1440, npcName = "Mastok Wrilehiss", questId = 1918, },
                { action = 26, questName = "Je'neu of the Earthen Ring", x = 0.737, y = 0.600, mapId = 1440, npcName = "Mastok Wrilehiss", questId = 824, },
                { action = 26, questName = "Satyr Horns", x = 0.731, y = 0.615, mapId = 1440, npcName = "Pixel", questId = 6441, },
                { action = 18, questName = "to Night Run", x = 0.722, y = 0.497, mapId = 1440, npcName = "", },
                { action = 8, questName = "Satyr Horns", x = 0.670, y = 0.560, mapId = 1440, npcName = "", questId = 6441, },
                { action = 20, questName = "Satyr Horns", x = 0.731, y = 0.615, mapId = 1440, npcName = "Pixel", questId = 6441, },
                { action = 16, questName = "to Zoram'gar Outpost", x = 0.732, y = 0.616, mapId = 1440, npcName = "Vhulgra", },
                { action = 20, questName = "King of the Foulweald", x = 0.119, y = 0.345, mapId = 1440, npcName = "Karang Amakkar", questId = 6621, },
                { action = 20, questName = "Je'neu of the Earthen Ring", x = 0.116, y = 0.343, mapId = 1440, npcName = "Je'neu Sancrea", questId = 824, },
                { action = 42, questName = "", x = 0.117, y = 0.341, mapId = 1440, npcName = "Wik'Tar", },
                { action = 22, questName = "to Sun Rock Retreat", npcName = "", },
                { action = 20, questName = "Ordanus", x = 0.459, y = 0.604, mapId = 1442, npcName = "Braelyn Firehand", questId = 1088, },
                { action = 34, questName = "The Den", x = 0.459, y = 0.604, mapId = 1442, npcName = "Braelyn Firehand", questId = 1089, },
                { action = 20, questName = "Jin'Zil's Forest Magic", x = 0.745, y = 0.979, mapId = 1442, npcName = "Witch Doctor Jin'Zil", questId = 1058, },
                { action = 11, questName = "", npcName = "", notes = "Use the Unstuck feature: Help Request > Character Stuck > Teleport to Graveyard. Or run across the street and die to the pack of Grimtotem.", },
                { action = 36, questName = "", x = 0.575, y = 0.613, mapId = 1442, npcName = "Spirit Healer", },
                { action = 43, questName = "", x = 0.454, y = 0.591, mapId = 1442, npcName = "Borand", },
                { class = "L", action = 16, questName = "to Orgrimmar", x = 0.451, y = 0.598, mapId = 1442, npcName = "Tharm", notes = "To train new rank of agony, shadow bolt, etc.", },
                { class = "DHMPrRSW", action = 16, questName = "to Thunder Bluff", x = 0.451, y = 0.598, mapId = 1442, npcName = "Tharm", },
                { class = "L", action = 40, questName = "", x = 0.480, y = 0.459, mapId = 1454, npcName = "Grol'dar", },
                { class = "L", action = 40, questName = "Pet", x = 0.475, y = 0.467, mapId = 1454, npcName = "Kurgul", },
                { class = "L", action = 16, questName = "to Thunder Bluff", x = 0.451, y = 0.639, mapId = 1454, npcName = "Doras", },
                { action = 20, questName = "The Sacred Flame", x = 0.550, y = 0.514, mapId = 1456, npcName = "Zangen Stonehoof", },
                { action = 26, questName = "The Sacred Flame (2)", x = 0.550, y = 0.514, mapId = 1456, npcName = "Zangen Stonehoof", questId = 1196, },
                { action = 20, questName = "The Flying Machine Airport", x = 0.228, y = 0.209, mapId = 1456, npcName = "Apothecary Zamah", questId = 1086, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end