local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "troll" then
    LiveGuide.registerLevel({
        guide = "LiveGuideTroll",
        race = "troll",
        title = "29-30",
        level = 29,
        nextLevel = 30,
        steps = function()
            return {
                { action = 42, questName = "", x = 0.211, y = 0.319, mapId = 1441, npcName = "Laer Stepperunner", notes = "Buy food - grinding ahead.", },
                { action = 8, questName = "Hypercapacitor Gizmo", x = 0.228, y = 0.246, mapId = 1441, npcName = "Enraged Panther", questId = 5151, notes = "Check if it's up. If not, hit it up on the way back. Make sure you get at least 1 other person.", },
                { action = 18, questName = "to Darkcloud Pinnacle", x = 0.313, y = 0.370, mapId = 1441, npcName = "", },
                { action = 7, questName = "Grimtotem Spying", x = 0.318, y = 0.326, mapId = 1441, npcName = "<Document Chest>", questId = 5064, notes = "These mobs are good to grind on. Kill everyone you see, but watch out for the Reavers.", },
                { action = 7, questName = "Grimtotem Spying", x = 0.338, y = 0.400, mapId = 1441, npcName = "<Document Chest>", questId = 5064, },
                { action = 8, questName = "Grimtotem Spying", x = 0.393, y = 0.415, mapId = 1441, npcName = "<Document Chest>", questId = 5064, },
                { action = 8, questName = "Wanted - Arnak Grimtotem", x = 0.381, y = 0.268, mapId = 1441, npcName = "Arnak Grimtotem", questId = 5147, },
                { action = 26, questName = "Free at Last", x = 0.379, y = 0.264, mapId = 1441, npcName = "Lakota Windsong", questId = 4904, },
                { action = 8, questName = "Free at Last", x = 0.379, y = 0.264, mapId = 1441, npcName = "Lakota Windsong", questId = 4904, },
                { action = 8, questName = "Sacred Fire", x = 0.370, y = 0.400, mapId = 1441, npcName = "<Incendia Agave>", questId = 5062, notes = "Dangerous mobs. Immune to Slow, immune to Bleed, immune to Frost. Can outrange the miss chance debuff by running. Beware going in the water.", },
                { action = 20, questName = "Hypercapacitor Gizmo", x = 0.214, y = 0.325, mapId = 1441, npcName = "Wizlo Bearingshiner", questId = 5151, notes = "If you haven't done it yet check again if there's anyone there and do it, otherwise try again next time.", },
                { action = 42, questName = "", x = 0.211, y = 0.319, mapId = 1441, npcName = "Laer Stepperunner", },
                { action = 18, questName = "up to Highperch", x = 0.146, y = 0.327, mapId = 1441, npcName = "", },
                { action = 8, questName = "Wind Rider", x = 0.110, y = 0.350, mapId = 1441, npcName = "<Highperch Wyvern Egg>", questId = 4767, },
                { action = 26, questName = "Homeward Bound", x = 0.179, y = 0.406, mapId = 1441, npcName = "Pao'ka Swiftmountain", questId = 4770, },
                { action = 8, questName = "Homeward Bound", x = 0.179, y = 0.406, mapId = 1441, npcName = "Pao'ka Swiftmountain", questId = 4770, },
                { action = 20, questName = "Homeward Bound", x = 0.215, y = 0.324, mapId = 1441, npcName = "Motega Firemane", questId = 4770, notes = "Check for Hypercapacitor Gizmo again.", },
                { action = 42, questName = "", x = 0.211, y = 0.319, mapId = 1441, npcName = "Laer Stepperunner", notes = "Buy food/water.", },
                { action = 20, questName = "Free at Last", x = 0.460, y = 0.516, mapId = 1441, npcName = "Thalia Amberhide", questId = 4904, },
                { action = 20, questName = "Grimtotem Spying", x = 0.457, y = 0.507, mapId = 1441, npcName = "Cliffwatcher Longhorn", questId = 5064, },
                { action = 20, questName = "Wanted - Arnak Grimtotem", x = 0.457, y = 0.507, mapId = 1441, npcName = "Cliffwatcher Longhorn", questId = 5147, },
                { action = 43, questName = "", x = 0.449, y = 0.507, mapId = 1441, npcName = "Starn", },
                { action = 20, questName = "Wind Rider", x = 0.449, y = 0.489, mapId = 1441, npcName = "Elu", questId = 4767, },
                { action = 29, questName = "A New Ore Sample", x = 0.674, y = 0.599, mapId = 1441, npcName = "Gravelsnout Surveyor", questId = 1153, notes = "Low drop chance. Grind in a triangle between the three spawns until you get it.", },
                { action = 29, questName = "A New Ore Sample", x = 0.664, y = 0.494, mapId = 1441, npcName = "Gravelsnout Surveyor", questId = 1153, },
                { action = 8, questName = "A New Ore Sample", x = 0.640, y = 0.468, mapId = 1441, npcName = "Gravelsnout Surveyor", questId = 1153, },
                { action = 18, questName = "to Camp E'thok", x = 0.187, y = 0.247, mapId = 1441, npcName = "", },
                { action = 19, questName = "to 37000 / 44300 L29", x = 0.178, y = 0.198, mapId = 1441, npcName = "", notes = "Catch Steelsnap if he spawns in the camp. The Galak Marauders have a relatively high chance to drop a BoE blue sword, [Heavy Marauder Scimitar].", },
                { class = "M", action = 19, questName = "to 39250 / 44300 L29", npcName = "", },
                { action = 8, questName = "Steelsnap", x = 0.140, y = 0.200, mapId = 1441, npcName = "Steelsnap", questId = 1131, },
                { action = 18, questName = "to Feralas", x = 0.075, y = 0.105, mapId = 1441, npcName = "", },
                { action = 11, questName = "in Feralas", x = 0.890, y = 0.412, mapId = 1444, npcName = "", },
                { action = 36, questName = "at Camp Mojache", x = 0.730, y = 0.445, mapId = 1444, npcName = "Spirit Healer", },
                { action = 17, questName = "at Camp Mojache", x = 0.754, y = 0.444, mapId = 1444, npcName = "Shyn", },
                { action = 16, questName = "to Thunder Bluff", x = 0.754, y = 0.444, mapId = 1444, npcName = "Shyn", },
                { action = 3, questName = "", x = 0.404, y = 0.518, mapId = 1456, npcName = "Auctioneer Stampi", },
                { action = 20, questName = "Steelsnap", x = 0.615, y = 0.809, mapId = 1456, npcName = "Melor Stonehoof", questId = 1131, },
                { action = 26, questName = "Frostmaw", x = 0.615, y = 0.809, mapId = 1456, npcName = "Melor Stonehoof", questId = 1136, },
                { action = 20, questName = "Sacred Fire", x = 0.699, y = 0.309, mapId = 1456, npcName = "Magatha Grimtotem", questId = 5062, },
                { action = 34, questName = "Arikara", x = 0.699, y = 0.309, mapId = 1456, npcName = "Magatha Grimtotem", questId = 5088, notes = "Quest is difficult, in an inconvenient place, and doesn't reward much XP. Good candidate for skipping. Accept and complete if you want.", },
                { class = "M", action = 40, questName = "Portals", x = 0.225, y = 0.169, mapId = 1456, npcName = "Birgitte Cranston", },
                { action = 16, questName = "to Camp Taurajo", x = 0.470, y = 0.498, mapId = 1456, npcName = "Tal", },
                { action = 20, questName = "A New Ore Sample", x = 0.451, y = 0.577, mapId = 1413, npcName = "Tatternack Steelforge", questId = 1153, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end