local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "human" then
    LiveGuide.registerLevel({
        guide = "LiveGuideHuman",
        race = "human",
        title = "10-11",
        level = 10,
        nextLevel = 11,
        steps = function()
            return {
                { action = 11, questName = "", x = 0.242, y = 0.744, mapId = 1429, npcName = "", },
                { action = 36, questName = "at Goldshire", x = 0.395, y = 0.605, mapId = 1429, npcName = "Spirit Healer", },
                { action = 20, questName = "Wanted: 'Hogger'", x = 0.421, y = 0.659, mapId = 1429, npcName = "Marshal Dughan", questId = 176, },
                { class = "M", action = 26, questName = "Speak with Jennea", x = 0.432, y = 0.662, mapId = 1429, npcName = "Zaldimar Wefhellt", questId = 1860, },
                { class = "M", action = 40, questName = "", x = 0.432, y = 0.662, mapId = 1429, npcName = "Zaldimar Wefhellt", },
                { class = "Pr", action = 26, questName = "Desperate Prayer", x = 0.433, y = 0.657, mapId = 1429, npcName = "Priestess Josetta", questId = 5636, },
                { class = "Pr", action = 40, questName = "", x = 0.433, y = 0.657, mapId = 1429, npcName = "Priestess Josetta", },
                { class = "R", action = 34, questName = "Seek Out SI: 7", x = 0.439, y = 0.659, mapId = 1429, npcName = "Keryn Sylvius", questId = 2205, notes = "dwarf/gnome version gives twice as much XP", },
                { class = "R", action = 40, questName = "", x = 0.439, y = 0.659, mapId = 1429, npcName = "Keryn Sylvius", },
                { class = "Pa", action = 40, questName = "", x = 0.411, y = 0.660, mapId = 1429, npcName = "Brother Wilhelm", },
                { class = "L", action = 26, questName = "Gakin's Summons", x = 0.445, y = 0.663, mapId = 1429, npcName = "Remen Marcot", questId = 1685, },
                { class = "L", action = 40, questName = "", x = 0.444, y = 0.662, mapId = 1429, npcName = "Maximillian Crowe", },
                { class = "W", action = 26, questName = "A Warrior's Training", x = 0.411, y = 0.658, mapId = 1429, npcName = "Lyria Du Lac", questId = 1638, },
                { class = "W", action = 40, questName = "", x = 0.411, y = 0.658, mapId = 1429, npcName = "Lyria Du Lac", },
                { class = "HPrLW", action = 40, questName = "Staves", x = 0.571, y = 0.577, mapId = 1453, npcName = "Woo Ping", },
                { class = "M", action = 40, questName = "Weapon Skills", x = 0.571, y = 0.577, mapId = 1453, npcName = "Woo Ping", },
                { class = "Pa", action = 40, questName = "Two-Handed Swords", x = 0.571, y = 0.577, mapId = 1453, npcName = "Woo Ping", },
                { class = "R", action = 40, questName = "One-Handed Swords", x = 0.571, y = 0.577, mapId = 1453, npcName = "Woo Ping", },
                { class = "MPrL", action = 6, questName = "[Coarse Thread]", x = 0.433, y = 0.741, mapId = 1453, npcName = "Alexandra Bolero", notes = "Up to 9 required to craft wand. May not need all 9 but it's very risky.", amount = "9", },
                { class = "MPrL", action = 52, questName = "[Bolt of Linen Cloth]", npcName = "", notes = "To 30 Tailoring. If you don't have enough linen it's still possible to complete the wand if you have other green items to disenchant instead.", },
                { class = "MPrL", action = 40, questName = "[Brown Linen Robe]", x = 0.437, y = 0.737, mapId = 1453, npcName = "Lawrence Schneider", },
                { class = "MPrL", action = 40, questName = "Enchanting", x = 0.431, y = 0.637, mapId = 1453, npcName = "Betty Quin", },
                { class = "MPrL", action = 52, questName = "[Brown Linen Robe]", npcName = "", questId = 176, notes = "may not need all 9 to reach 10 enchanting skill. each disenchant gives a skill point", amount = "9", },
                { class = "MPrL", action = 6, questName = "[Copper Rod]", x = 0.428, y = 0.644, mapId = 1453, npcName = "Jessara Cordell", amount = "1", },
                { class = "MPrL", action = 6, questName = "[Simple Wood]", x = 0.428, y = 0.644, mapId = 1453, npcName = "Jessara Cordell", amount = "1", },
                { class = "MPrL", action = 53, questName = "[Brown Linen Robe]", npcName = "", amount = "9", },
                { class = "MPrL", action = 52, questName = "[Runed Copper Rod]", npcName = "", notes = "this gives a skill if you craft it early enough, but you need Lesser Magic Essence which has a 20% chance from the robes, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH", },
                { class = "MPrL", action = 40, questName = "[Lesser Magic Wand]", x = 0.431, y = 0.637, mapId = 1453, npcName = "Betty Quin", },
                { class = "MPrL", action = 52, questName = "[Lesser Magic Wand]", npcName = "", notes = "Lesser Magic Essence has a 20% chance from green gear, 80% chance from green weapons (if you have any to disenchant), or can be bought for 8s from the vendor or on the AH", },
                { class = "M", action = 18, questName = "to Wizard's Sanctum", x = 0.375, y = 0.822, mapId = 1453, npcName = "", },
                { class = "M", action = 20, questName = "Speak with Jennea", x = 0.385, y = 0.793, mapId = 1453, npcName = "Jennea Cannon", questId = 1860, },
                { class = "M", action = 34, questName = "Mirror Lake", x = 0.385, y = 0.793, mapId = 1453, npcName = "Jennea Cannon", questId = 1861, notes = "or do it now if you want the rewards. 850 XP for ~7 minutes, not great", },
                { class = "Pr", action = 20, questName = "Desperate Prayer", x = 0.386, y = 0.260, mapId = 1453, npcName = "High Priestess Laurena", questId = 5636, },
                { class = "L", action = 18, questName = "to The Slaughtered Lamb", x = 0.290, y = 0.743, mapId = 1453, npcName = "", },
                { class = "L", action = 20, questName = "Gakin's Summons", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1685, },
                { class = "L", action = 26, questName = "Surena Caledon", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1688, },
                { class = "W", action = 20, questName = "A Warrior's Training", x = 0.743, y = 0.373, mapId = 1453, npcName = "Harry Burlguard", questId = 1638, },
                { class = "W", action = 26, questName = "Bartleby the Drunk", x = 0.743, y = 0.373, mapId = 1453, npcName = "Harry Burlguard", questId = 1639, },
                { class = "W", action = 20, questName = "Bartleby the Drunk", x = 0.730, y = 0.370, mapId = 1453, npcName = "Bartleby", questId = 1639, },
                { class = "W", action = 26, questName = "Beat Bartleby", x = 0.730, y = 0.370, mapId = 1453, npcName = "Bartleby", questId = 1640, },
                { class = "W", action = 8, questName = "Beat Bartleby", x = 0.730, y = 0.370, mapId = 1453, npcName = "Bartleby", questId = 1640, },
                { class = "W", action = 20, questName = "Beat Bartleby", x = 0.730, y = 0.370, mapId = 1453, npcName = "Bartleby", questId = 1640, },
                { class = "W", action = 26, questName = "Bartleby's Mug", x = 0.730, y = 0.370, mapId = 1453, npcName = "Bartleby", questId = 1665, },
                { class = "W", action = 20, questName = "Bartleby's Mug", x = 0.743, y = 0.373, mapId = 1453, npcName = "Harry Burlguard", questId = 1665, },
                { class = "W", action = 26, questName = "Marshal Haggard", x = 0.743, y = 0.373, mapId = 1453, npcName = "Harry Burlguard", questId = 1666, },
                { class = "DHMPaPrRW", action = 20, questName = "Elmore's Task", x = 0.518, y = 0.121, mapId = 1453, npcName = "Grimand Elmore", questId = 1097, },
                { class = "DHMPaPrRW", action = 26, questName = "Stormpike's Delivery", x = 0.518, y = 0.121, mapId = 1453, npcName = "Grimand Elmore", questId = 353, },
                { class = "DHMPaPrRW", action = 18, questName = "to Deeprun Tram", x = 0.639, y = 0.082, mapId = 1453, npcName = "", },
                { class = "L", action = 8, questName = "Surena Caledon", x = 0.710, y = 0.808, mapId = 1429, npcName = "Surena Caledon", questId = 1688, },
                { class = "L", action = 8, questName = "Red Linen Goods", x = 0.710, y = 0.790, mapId = 1429, npcName = "", questId = 83, },
                { class = "L", action = 20, questName = "Red Linen Goods", x = 0.795, y = 0.688, mapId = 1429, npcName = "Sara Timberlain", questId = 83, },
                { class = "L", action = 20, questName = "Cloth and Leather Armor", x = 0.795, y = 0.688, mapId = 1429, npcName = "Sara Timberlain", questId = 59, },
                { class = "L", action = 18, questName = "to Redridge Mountains", x = 0.940, y = 0.724, mapId = 1429, npcName = "", },
                { class = "L", action = 11, questName = "", x = 0.090, y = 0.760, mapId = 1433, npcName = "Tarantula", },
                { class = "L", action = 36, questName = "", x = 0.208, y = 0.566, mapId = 1433, npcName = "Spirit Healer", },
                { class = "L", action = 17, questName = "at Lakeshire", x = 0.306, y = 0.594, mapId = 1433, npcName = "Ariena Stormfeather", },
                { class = "L", action = 16, questName = "to Stormwind", x = 0.306, y = 0.594, mapId = 1433, npcName = "Ariena Stormfeather", },
                { class = "L", action = 20, questName = "Surena Caledon", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1688, },
                { class = "L", action = 26, questName = "The Binding", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1689, },
                { class = "L", action = 18, questName = "down one level", x = 0.249, y = 0.795, mapId = 1453, npcName = "", },
                { class = "L", action = 18, questName = "right", x = 0.234, y = 0.795, mapId = 1453, npcName = "", },
                { class = "L", action = 8, questName = "The Binding", x = 0.251, y = 0.775, mapId = 1453, npcName = ">Summoning Circle<", questId = 1689, },
                { class = "L", action = 20, questName = "The Binding", x = 0.253, y = 0.786, mapId = 1453, npcName = "Gakin the Darkbinder", questId = 1689, },
                { class = "L", action = 20, questName = "Elmore's Task", x = 0.518, y = 0.121, mapId = 1453, npcName = "Grimand Elmore", questId = 1097, },
                { class = "L", action = 26, questName = "Stormpike's Delivery", x = 0.518, y = 0.121, mapId = 1453, npcName = "Grimand Elmore", questId = 353, },
                { class = "L", action = 18, questName = "to Deeprun Tram", x = 0.639, y = 0.082, mapId = 1453, npcName = "", },
                { action = 18, questName = "to Ironforge station", x = 0.639, y = 0.082, mapId = 1453, npcName = ">Deeprun Tram<", },
                { action = 26, questName = "Deeprun Rat Roundup", npcName = "Monty", questId = 6661, },
                { action = 8, questName = "Deeprun Rat Roundup", npcName = "", questId = 6661, },
                { action = 20, questName = "Deeprun Rat Roundup", npcName = "Monty", questId = 6661, },
                { action = 34, questName = "Me Brother, Nipsy", npcName = "Monty", questId = 6662, },
                { action = 18, questName = "to Ironforge", npcName = "", },
                { class = "W", action = 40, questName = "Thrown", x = 0.622, y = 0.896, mapId = 1455, npcName = "Bixi Wobblebonk", },
                { class = "R", action = 40, questName = "One-Handed Maces", x = 0.612, y = 0.895, mapId = 1455, npcName = "Buliwyf Stonehand", },
                { action = 17, questName = "", x = 0.555, y = 0.477, mapId = 1455, npcName = "Gryth Thurden", },
                { action = 33, questName = "at Ironforge", x = 0.181, y = 0.515, mapId = 1455, npcName = "Innkeeper Firebrew", },
                { action = 18, questName = "to Dun Morogh", x = 0.152, y = 0.857, mapId = 1455, npcName = "", },
                { action = 18, questName = "to Dun Morogh", x = 0.535, y = 0.350, mapId = 1426, npcName = "", },
                { action = 18, questName = "down esports ♦♦", x = 0.541, y = 0.394, mapId = 1426, npcName = "", },
                { action = 26, questName = "Protecting the Herd", x = 0.631, y = 0.498, mapId = 1426, npcName = "Rudra Amberstill", questId = 314, },
                { action = 18, questName = "up shortcut", x = 0.624, y = 0.502, mapId = 1426, npcName = "", },
                { action = 8, questName = "Protecting the Herd", x = 0.620, y = 0.470, mapId = 1426, npcName = "Vagash", questId = 314, notes = "Elite -- find a group or skip. Gives good rewards so it's worth doing. Best strategy to complete this quest is to use a ranged attack to pull and slow Vagash as you kite him to the Guard NPCs on the road. You must do 50% of the damage to Vagash to receive credit for the kill.", },
                { action = 20, questName = "Protecting the Herd", x = 0.631, y = 0.498, mapId = 1426, npcName = "Rudra Amberstill", questId = 314, },
                { action = 26, questName = "The Public Servant", x = 0.687, y = 0.560, mapId = 1426, npcName = "Senator Mehr Stonehallow", questId = 433, },
                { action = 43, questName = "", x = 0.689, y = 0.560, mapId = 1426, npcName = "Frast Dokner", },
                { action = 26, questName = "Those Blasted Troggs!", x = 0.691, y = 0.563, mapId = 1426, npcName = "Foreman Stonebrow", questId = 432, },
                { action = 8, questName = "The Public Servant", x = 0.707, y = 0.566, mapId = 1426, npcName = "", questId = 433, },
                { action = 8, questName = "Those Blasted Troggs!", x = 0.707, y = 0.566, mapId = 1426, npcName = "", questId = 432, },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end