local raceEn = select(1, UnitRace("player"))
local classEn = select(1, UnitClass("player"))
if raceEn:gsub("%s+", ""):lower() == "nightelf" then
    LiveGuide.registerLevel({
        guide = "LiveGuideNightelf",
        race = "nightelf",
        title = "59-60",
        level = 59,
        steps = function()
            return {
                { action = 22, questName = "to Menethil Harbor", npcName = "", },
                { action = 16, questName = "to Ironforge", x = 0.095, y = 0.597, mapId = 1437, npcName = "Shellei Brondir", },
                { action = 38, questName = "for Blackrock Depths", npcName = "", notes = "Yes let's do it again. You'll complete your Onyxia attunement, you'll have the key this time, and you'll have the quest for the final boss as well.", },
                { action = 33, questName = "at Ironforge", x = 0.182, y = 0.514, mapId = 1455, npcName = "Innkeeper Firebrew", },
                { action = 20, questName = "The Bearer of Bad News", x = 0.391, y = 0.562, mapId = 1455, npcName = "King Magni Bronzebeard", questId = 4361, },
                { action = 26, questName = "The Fate of the Kingdom", x = 0.391, y = 0.562, mapId = 1455, npcName = "King Magni Bronzebeard", questId = 4362, notes = "Final BRD quest.", },
                { action = 16, questName = "to Morgan's Vigil", x = 0.555, y = 0.477, mapId = 1455, npcName = "Gryth Thurden", },
                { action = 20, questName = "The Good Stuff", x = 0.846, y = 0.687, mapId = 1428, npcName = "Oralius", questId = 4286, },
                { action = 20, questName = "Abandoned Hope", x = 0.847, y = 0.690, mapId = 1428, npcName = "Marshal Maxwell", questId = 4242, },
                { action = 20, questName = "Overmaster Pyron", x = 0.854, y = 0.701, mapId = 1428, npcName = "Jalinda Sprig", questId = 4262, },
                { action = 26, questName = "Incendius!", x = 0.854, y = 0.701, mapId = 1428, npcName = "Jalinda Sprig", questId = 4263, },
                { action = 20, questName = "A Taste of Flame (2)", x = 0.951, y = 0.316, mapId = 1428, npcName = "Cyrus Therepentous", questId = 4024, },
                { action = 18, questName = "to Blackrock Mountain", x = 0.294, y = 0.479, mapId = 1428, npcName = "", },
                { action = 13, questName = "Blackrock Depths", x = 0.293, y = 0.372, mapId = 1428, npcName = "", },
                { action = 25, questName = "[A Crumpled Up Note]", npcName = "", },
                { action = 2, questName = "A Crumpled Up Note", npcName = "[A Crumpled Up Note]", questId = 4264, },
                { action = 20, questName = "A Crumpled Up Note", npcName = "Marshal Windsor", questId = 4264, },
                { action = 26, questName = "A Shred of Hope", npcName = "Marshal Windsor", questId = 4282, },
                { action = 18, questName = "through door", npcName = "<East Garrison Door>", },
                { action = 23, questName = "out window to Incendius", npcName = "", },
                { action = 8, questName = "Incendius!", npcName = "Lord Incendius", questId = 4263, },
                { action = 18, questName = "through door", npcName = "<Shadowforge Gate>", notes = "Go through the Giant Gate to Bael'gar and then back to through the East Garrison Door again.", },
                { action = 41, questName = "", npcName = "<The Shadowforge Lock>", },
                { action = 7, questName = "A Shred of Hope", npcName = "General Angerforge", questId = 4282, },
                { action = 8, questName = "A Shred of Hope", npcName = "Golem Lord Argelmach", questId = 4282, },
                { action = 8, questName = "Ribbly Screwspigot", npcName = "Ribbly Screwspigot", questId = 4136, },
                { action = 20, questName = "A Shred of Hope", npcName = "Marshal Windsor", questId = 4282, },
                { action = 26, questName = "Jail Break!", npcName = "Marshal Windsor", questId = 4322, },
                { action = 8, questName = "Jail Break!", npcName = "Marshal Windsor", questId = 4322, },
                { action = 8, questName = "Attunement to the Core", npcName = "<Core Fragment>", questId = 7848, },
                { action = 8, questName = "The Fate of the Kingdom", npcName = "Emperor Dagran Thaurissan", questId = 4362, notes = "Princess Moira must survive.", },
                { action = 20, questName = "The Fate of the Kingdom", npcName = "Princess Moira Bronzebeard", questId = 4362, },
                { action = 26, questName = "The Princess's Surprise", npcName = "Princess Moira Bronzebeard", questId = 4363, },
                { action = 18, questName = "into Molten Core", npcName = "", notes = "Convert to raid and zone in the green portal near where you collected the Core Fragment.", },
                { action = 18, questName = "back out portal to Blackrock Mountain", npcName = "", },
                { action = 20, questName = "Attunement to the Core", npcName = "Lothos Riftwaker", questId = 7848, },
                { action = 11, questName = "", npcName = "", notes = "Throw yourself in the lava or something.", },
                { action = 36, questName = "at Thorium Point", x = 0.355, y = 0.228, mapId = 1427, npcName = "Spirit Healer", },
                { action = 16, questName = "to Morgan's Vigil", x = 0.379, y = 0.309, mapId = 1427, npcName = "Lanie Reed", },
                { action = 20, questName = "Jail Break!", x = 0.847, y = 0.690, mapId = 1428, npcName = "Marshal Maxwell", questId = 4322, },
                { action = 26, questName = "Stormwind Rendezvous", x = 0.847, y = 0.690, mapId = 1428, npcName = "Marshal Maxwell", questId = 6402, },
                { action = 20, questName = "Incendius!", x = 0.854, y = 0.701, mapId = 1428, npcName = "Jalinda Sprig", questId = 4263, },
                { action = 20, questName = "The Heart of the Mountain", x = 0.652, y = 0.239, mapId = 1428, npcName = "Maxwort Uberglint", questId = 4123, },
                { action = 20, questName = "Ribbly Screwspigot", x = 0.661, y = 0.220, mapId = 1428, npcName = "Yuka Screwspigot", questId = 4136, },
                { action = 16, questName = "to Stormwind", x = 0.843, y = 0.683, mapId = 1428, npcName = "Borgus Stoutarm", },
                { action = 8, questName = "Stormwind Rendezvous", x = 0.705, y = 0.851, mapId = 1453, npcName = "Squire Rowe", questId = 6402, },
                { action = 20, questName = "Stormwind Rendezvous", x = 0.697, y = 0.861, mapId = 1453, npcName = "Reginald Windsor", questId = 6402, },
                { action = 26, questName = "The Great Masquerade", x = 0.697, y = 0.861, mapId = 1453, npcName = "Reginald Windsor", questId = 6403, },
                { action = 8, questName = "The Great Masquerade", x = 0.680, y = 0.301, mapId = 1453, npcName = "Reginald Windsor", questId = 6403, },
                { action = 20, questName = "The Blightcaller Cometh", x = 0.782, y = 0.180, mapId = 1453, npcName = "Highlord Bolvar Fordragon", questId = 6186, },
                { action = 26, questName = "Order Must Be Restored", x = 0.782, y = 0.180, mapId = 1453, npcName = "Highlord Bolvar Fordragon", questId = 6187, notes = "This quest gives some good pre-raid items.", },
                { action = 20, questName = "The Great Masquerade", x = 0.782, y = 0.180, mapId = 1453, npcName = "Highlord Bolvar Fordragon", questId = 6403, },
                { action = 26, questName = "The Dragon's Eye", x = 0.782, y = 0.180, mapId = 1453, npcName = "Highlord Bolvar Fordragon", questId = 6501, },
                { action = 22, questName = "to Ironforge", npcName = "", },
                { action = 20, questName = "The Princess's Surprise", x = 0.391, y = 0.562, mapId = 1455, npcName = "King Magni Bronzebeard", questId = 4363, },
                { action = 16, questName = "to Menethil Harbor", x = 0.555, y = 0.477, mapId = 1455, npcName = "Gryth Thurden", },
                { action = 18, questName = "to Auberdine", x = 0.046, y = 0.571, mapId = 1437, npcName = ">Ship<", },
                { action = 16, questName = "to Rut'theran Village", x = 0.363, y = 0.456, mapId = 1439, npcName = "Caylais Moonfeather", },
                { action = 20, questName = "Guardians of the Altar", x = 0.555, y = 0.920, mapId = 1438, npcName = "Erelas Ambersky", questId = 4901, },
                { action = 26, questName = "Wildkin of Elune", x = 0.555, y = 0.920, mapId = 1438, npcName = "Erelas Ambersky", questId = 4902, },
                { action = 18, questName = "to Darnassus", x = 0.559, y = 0.896, mapId = 1438, npcName = "", },
                { action = 20, questName = "Wildkin of Elune", x = 0.348, y = 0.093, mapId = 1457, npcName = "Arch Druid Fandral Staghelm", questId = 4902, },
                { action = 18, questName = "to Rut'theran Village", x = 0.300, y = 0.413, mapId = 1457, npcName = "", },
                { action = 16, questName = "to Everlook", x = 0.584, y = 0.940, mapId = 1438, npcName = "Vesprystus", },
                { action = 20, questName = "Are We There, Yeti? (3)", x = 0.609, y = 0.376, mapId = 1452, npcName = "Umi Rumplesnicker", questId = 5163, },
                { action = 26, questName = "Tinkee Steamboil", x = 0.616, y = 0.386, mapId = 1452, npcName = "Felnok Steelspring", questId = 4907, notes = "Leads to an UBRS quest.", },
                { action = 18, questName = "to Mazthoril", x = 0.570, y = 0.500, mapId = 1452, npcName = "", },
                { action = 54, questName = "to mountaintop", x = 0.526, y = 0.558, mapId = 1452, npcName = "<Rune of Mazthoril>", },
                { action = 20, questName = "The Dragon's Eye", x = 0.545, y = 0.512, mapId = 1452, npcName = "Haleh", questId = 6501, },
                { action = 26, questName = "Drakefire Amulet", x = 0.545, y = 0.512, mapId = 1452, npcName = "Haleh", questId = 6502, notes = "Final part of Onyxia attunement.", },
                { class = "D", action = 16, questName = "to Talonbranch Glade", x = 0.623, y = 0.366, mapId = 1452, npcName = "Maethrya", },
                { class = "HMPaPrRLW", action = 16, questName = "to Moonglade", x = 0.623, y = 0.366, mapId = 1452, npcName = "Maethrya", },
                { class = "HMPaPrRLW", action = 20, questName = "Umber, Archivist", x = 0.449, y = 0.356, mapId = 1450, npcName = "Umber", questId = 6844, },
                { class = "HMPaPrRLW", action = 26, questName = "Uncovering Past Secrets", x = 0.449, y = 0.356, mapId = 1450, npcName = "Umber", questId = 6845, },
                { class = "HMPaPrRLW", action = 20, questName = "Uncovering Past Secrets", x = 0.517, y = 0.451, mapId = 1450, npcName = "Rabine Saturna", questId = 6845, },
                { class = "x", action = 20, questName = "A Reliquary of Purity", x = 0.517, y = 0.451, mapId = 1450, npcName = "Rabine Saturna", questId = 5527, },
                { class = "x", action = 26, questName = "Shards of the Felvine", x = 0.517, y = 0.451, mapId = 1450, npcName = "Rabine Saturna", questId = 5526, notes = "Dire Maul: East quest", },
                { class = "HMPaPrRLW", action = 30, questName = "Under the Chitin Was...", x = 0.449, y = 0.356, mapId = 1450, npcName = "Umber", questId = 1185, },
                { class = "HMPaPrRLW", action = 16, questName = "to Talonbranch Glade", x = 0.481, y = 0.673, mapId = 1450, npcName = "Sindrayl", },
                { action = 20, questName = "Words of the High Chief", x = 0.511, y = 0.818, mapId = 1448, npcName = "Kelek Skykeeper", questId = 5128, },
                { action = 20, questName = "Linken's Memory", x = 0.514, y = 0.815, mapId = 1448, npcName = "Eridan Bluewind", questId = 3942, },
                { action = 26, questName = "Silver Heart", x = 0.514, y = 0.815, mapId = 1448, npcName = "Eridan Bluewind", questId = 4084, },
                { action = 8, questName = "Silver Heart", x = 0.540, y = 0.250, mapId = 1448, npcName = "", questId = 4084, },
                { action = 19, questName = "to 194000 / 209800 L59", x = 0.430, y = 0.160, mapId = 1448, npcName = "", notes = "They drop Felcloth and Demonic Runes.", },
                { action = 20, questName = "Silver Heart", x = 0.514, y = 0.815, mapId = 1448, npcName = "Eridan Bluewind", questId = 4084, },
                { action = 26, questName = "Aquementas", x = 0.514, y = 0.815, mapId = 1448, npcName = "Eridan Bluewind", questId = 4005, },
                { action = 16, questName = "to Talrendis Point", x = 0.625, y = 0.242, mapId = 1448, npcName = "Mishellena", },
                { action = 20, questName = "Poisoned Water", x = 0.793, y = 0.737, mapId = 1447, npcName = "Duke Hydraxis", questId = 6804, },
                { action = 20, questName = "Stormers and Rumblers", x = 0.793, y = 0.737, mapId = 1447, npcName = "Duke Hydraxis", questId = 6805, },
                { action = 26, questName = "Eye of the Emberseer", x = 0.793, y = 0.737, mapId = 1447, npcName = "Duke Hydraxis", questId = 6821, notes = "Completing this quest chain unlocks [Aqual Quintessence], an item necessary to complete Molten Core.", },
                { action = 1000, questName = "", npcName = "", },
            }
        end
    })
end